# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-16 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("marker", models.IntegerField(blank=True, null=True)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "typo3_category", "managed": False},
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("allday", models.BooleanField()),
                ("title", models.TextField(blank=True, null=True)),
                ("organizer", models.CharField(blank=True, max_length=256, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("teaser", models.TextField(blank=True, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("register", models.BooleanField()),
                ("registration_end", models.DateTimeField(blank=True, null=True)),
                ("attending_fees", models.BooleanField()),
                ("link", models.CharField(blank=True, max_length=512, null=True)),
                ("dfp_points", models.IntegerField(blank=True, null=True)),
                ("contact", models.CharField(blank=True, max_length=256, null=True)),
                ("email", models.CharField(blank=True, max_length=256, null=True)),
                ("last_modified", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "typo3_event",
                "ordering": ("start", "end"),
                "get_latest_by": "start",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                )
            ],
            options={"db_table": "typo3_eventcategory", "managed": False},
        ),
        migrations.CreateModel(
            name="EventMedia",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("alternative", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(blank=True, null=True)),
                ("preview", models.BooleanField()),
            ],
            options={
                "db_table": "typo3_eventmedia",
                "ordering": ("-preview", "-order"),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={"db_table": "typo3_group", "managed": False},
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("flag", models.CharField(blank=True, max_length=2, null=True)),
                ("isocode", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={"db_table": "typo3_language", "managed": False},
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("path", models.TextField()),
                ("mimetype", models.CharField(blank=True, max_length=256, null=True)),
                ("filename", models.CharField(blank=True, max_length=256, null=True)),
                ("size", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={"db_table": "typo3_media", "managed": False},
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("teaser", models.TextField(blank=True, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("author", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
                ("tags", models.IntegerField(blank=True, null=True)),
                ("topnews", models.BooleanField()),
                ("last_modified", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "typo3_news",
                "ordering": ("-datetime",),
                "get_latest_by": "datetime",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                )
            ],
            options={"db_table": "typo3_newscategory", "managed": False},
        ),
        migrations.CreateModel(
            name="NewsMedia",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("alternative", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(blank=True, null=True)),
                ("preview", models.BooleanField()),
            ],
            options={
                "db_table": "typo3_newsmedia",
                "ordering": ("-preview", "-order"),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("private", models.BooleanField()),
            ],
            options={"db_table": "typo3_source", "managed": False},
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("url", models.URLField()),
            ],
            options={"db_table": "typo3_storage", "managed": False},
        ),
        migrations.CreateModel(
            name="ZMFCourse",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("page", models.IntegerField()),
                ("last_modified", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={"db_table": "typo3_zmf_course", "managed": False},
        ),
        migrations.CreateModel(
            name="DjangoSource",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="typo3.Source",
                    ),
                ),
                ("private", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DjangoStorage",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="typo3.Storage",
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
    ]
