# Generated by Django 4.2.28 on 2026-05-29 14:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import outpost.django.typo3.fields
import outpost.django.typo3.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE FOREIGN TABLE typo3.category (
                    uid integer,
                    tstamp bigint,
                    crdate bigint,
                    deleted smallint,
                    hidden smallint,
                    starttime bigint,
                    endtime bigint,
                    title text,
                    description text,
                    parent integer,
                    items integer,
                    images integer,
                    shortcut integer,
                    tx_odsosm_marker integer,
                    slug character varying
                )
                SERVER typo3
                OPTIONS (
                    dbname 'typo3-production',
                    table_name 'sys_category'
                )
            """,
            reverse_sql="""
                DROP FOREIGN TABLE typo3.category
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE FOREIGN TABLE typo3.file_reference (
                    uid integer,
                    pid integer,
                    tstamp bigint,
                    crdate bigint,
                    cruser_id integer,
                    sorting integer,
                    deleted smallint,
                    hidden smallint,
                    uid_local integer,
                    uid_foreign integer,
                    tablenames character varying,
                    fieldname character varying,
                    sorting_foreign integer,
                    table_local character varying,
                    title character varying,
                    description text,
                    alternative text,
                    link character varying,
                    downloadname text,
                    showinpreview smallint,
                    crop text,
                    autoplay smallint
                )
                SERVER typo3
                OPTIONS (
                    dbname 'typo3-production',
                    table_name 'sys_file_reference'
                )
            """,
            reverse_sql="""
                DROP FOREIGN TABLE typo3.file_reference
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE FOREIGN TABLE typo3.news (
                    uid integer,
                    pid integer,
                    tstamp bigint,
                    crdate bigint,
                    deleted smallint,
                    hidden smallint,
                    starttime bigint,
                    endtime bigint,
                    sorting integer,
                    fe_group character varying,
                    title text,
                    teaser text,
                    bodytext text,
                    datetime bigint,
                    archive bigint,
                    author text,
                    author_email text,
                    categories integer,
                    related integer,
                    related_from integer,
                    related_files text,
                    related_links text,
                    type character varying,
                    keywords text,
                    tags integer,
                    media text,
                    internalurl text,
                    externalurl text,
                    istopnews integer,
                    content_elements text,
                    path_segment text,
                    alternative_title text,
                    description text,
                    fal_related_files integer,
                    fal_media integer,
                    is_event smallint,
                    full_day smallint,
                    event_end integer,
                    organizer integer,
                    location integer,
                    organizer_simple character varying,
                    location_simple character varying,
                    www character varying,
                    contact_name character varying,
                    contact_email character varying,
                    register smallint,
                    registration_end integer,
                    attendingfees smallint,
                    dfppoints integer,
                    t3ver_wsid integer,
                    attendingfees_info text
                )
                SERVER typo3
                OPTIONS (
                    dbname 'typo3-production',
                    table_name 'tx_news_domain_model_news'
                )
            """,
            reverse_sql="""
                DROP FOREIGN TABLE typo3.news
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE FOREIGN TABLE typo3.news_links (
                    uid integer,
                    pid integer,
                    tstamp bigint,
                    crdate bigint,
                    cruser_id integer,
                    sorting integer,
                    deleted smallint,
                    hidden smallint,
                    parent integer,
                    title character varying,
                    description text,
                    uri text
                )
                SERVER typo3
                OPTIONS (
                    dbname 'typo3-production',
                    table_name 'tx_news_domain_model_link'
                )
            """,
            reverse_sql="""
                DROP FOREIGN TABLE typo3.news_links
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE FOREIGN TABLE typo3.file (
                    uid integer,
                    pid integer,
                    tstamp bigint,
                    type character varying,
                    storage integer,
                    identifier text,
                    extension character varying,
                    mime_type character varying,
                    name text,
                    sha1 character varying,
                    size bigint,
                    creation_date bigint,
                    modification_date bigint,
                    last_indexed bigint,
                    missing smallint,
                    metadata integer,
                    identifier_hash character varying,
                    folder_hash character varying
                )
                SERVER typo3
                OPTIONS (
                    dbname 'typo3-production',
                    table_name 'sys_file'
                )
            """,
            reverse_sql="""
                DROP FOREIGN TABLE typo3.file
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE FOREIGN TABLE typo3.category_record (
                    uid_local integer,
                    uid_foreign integer,
                    tablenames character varying,
                    sorting integer,
                    sorting_foreign integer,
                    fieldname character varying
                )
                SERVER typo3
                OPTIONS (
                    dbname 'typo3-production',
                    table_name 'sys_category_record_mm'
                )
            """,
            reverse_sql="""
                DROP FOREIGN TABLE typo3.category_record
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE FOREIGN TABLE typo3.content (
                    uid integer,
                    pid integer,
                    tstamp bigint,
                    crdate bigint,
                    cruser_id integer,
                    sorting integer,
                    deleted smallint,
                    hidden smallint,
                    ctype character varying,
                    header character varying,
                    bodytext text,
                    header_link character varying,
                    list_type character varying,
                    tx_news_related_news integer,
                    subheader text,
                    mugce_link_label text,
                    mugce_subheader text,
                    mugce_caption text,
                    mugce_text_3 text,
                    mugce_text_4 text
                )
                SERVER typo3
                OPTIONS (
                    dbname 'typo3-production',
                    table_name 'tt_content'
                )
            """,
            reverse_sql="""
                DROP FOREIGN TABLE typo3.content
            """,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE VIEW public.typo3_category AS SELECT
                            uid AS id,
                            CASE starttime
                                WHEN 0 THEN CAST(NULL AS TIMESTAMPTZ)
                                ELSE UNIX_TO_TIME(CAST((starttime) AS DOUBLE))
                                END AS start,
                            CASE endtime
                                WHEN 0 THEN CAST(NULL AS TIMESTAMPTZ)
                                ELSE UNIX_TO_TIME(CAST((endtime) AS DOUBLE))
                                END AS "end",
                            title,
                            description,
                            parent,
                            tx_odsosm_marker AS marker
                        FROM typo3.category
                        WHERE
                            ((deleted = 0) AND
                            (hidden = 0))
                    """,
                    reverse_sql="""
                        DROP VIEW public.typo3_category
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Category",
                    fields=[
                        ("id", models.IntegerField(primary_key=True, serialize=False)),
                        ("title", models.TextField(blank=True, null=True)),
                        ("description", models.TextField(blank=True, null=True)),
                        ("marker", models.IntegerField(blank=True, null=True)),
                        ("start", models.DateTimeField(blank=True, null=True)),
                        ("end", models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "typo3_category",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.typo3_event AS
                        SELECT uid AS id,
                            pid AS source_id,
                            to_timestamp((datetime)::double precision) AS start,
                                CASE event_end
                                    WHEN 0 THEN (((to_timestamp((datetime)::double precision))::date + '24:00:00'::interval))::timestamp with time zone
                                    ELSE to_timestamp((event_end)::double precision)
                                END AS "end",
                            ((full_day)::integer)::boolean AS allday,
                            public.html_unescape(title) AS title,
                            NULLIF(btrim((organizer_simple)::text, ' '::text), ''::text) AS organizer,
                            NULLIF(btrim((location_simple)::text, ' '::text), ''::text) AS location,
                            public.html_unescape(teaser) AS teaser,
                            public.html_unescape(bodytext) AS body,
                            regexp_split_to_array(NULLIF(btrim(keywords), ''::text), '\s*,\s*'::text) AS keywords,
                            NULLIF(btrim(description), ''::text) AS description,
                            ((register)::integer)::boolean AS register,
                                CASE
                                    WHEN (registration_end > 0) THEN to_timestamp((registration_end)::double precision)
                                    ELSE NULL::timestamp with time zone
                                END AS registration_end,
                            ((attendingfees)::integer)::boolean AS attending_fees,
                            NULLIF(btrim(attendingfees_info), ''::text) AS attending_fees_info,
                            NULLIF(btrim((www)::text, ' '::text), ''::text) AS link,
                                CASE
                                    WHEN (dfppoints > 0) THEN dfppoints
                                    ELSE NULL::integer
                                END AS dfp_points,
                            NULLIF(btrim((contact_name)::text, ' '::text), ''::text) AS contact,
                            NULLIF(btrim((contact_email)::text, ' '::text), ''::text) AS email,
                            to_timestamp((tstamp)::double precision) AS last_modified,
                            ( SELECT fr.uid_local
                                FROM typo3.file_reference fr
                                WHERE
                                (
                                    (fr.uid_foreign = n.uid) AND
                                    ((fr.tablenames)::text = 'tx_news_domain_model_news'::text) AND
                                    ((fr.fieldname)::text = 'fal_media'::text) AND
                                    (fr.showinpreview = 1) AND
                                    (fr.hidden = 0) AND
                                    (fr.deleted = 0))
                                ORDER BY fr.sorting
                                LIMIT 1) AS header_image_id
                        FROM typo3.news n
                        WHERE
                        (
                            (datetime <> 0) AND
                            (deleted = 0) AND
                            (hidden = 0) AND
                            (t3ver_wsid = 0) AND
                            (is_event = 1))
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.typo3_event
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Event",
                    fields=[
                        ("id", models.IntegerField(primary_key=True, serialize=False)),
                        ("start", models.DateTimeField(blank=True, null=True)),
                        ("end", models.DateTimeField(blank=True, null=True)),
                        ("allday", models.BooleanField()),
                        ("title", models.TextField(blank=True, null=True)),
                        (
                            "organizer",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        ("location", models.TextField(blank=True, null=True)),
                        ("teaser", models.TextField(blank=True, null=True)),
                        (
                            "body",
                            outpost.django.typo3.fields.RichTextField(
                                blank=True,
                                media_model=outpost.django.typo3.models.Media,
                                null=True,
                            ),
                        ),
                        (
                            "keywords",
                            django.contrib.postgres.fields.ArrayField(
                                base_field=models.TextField(blank=True), size=None
                            ),
                        ),
                        ("description", models.TextField(blank=True, null=True)),
                        ("register", models.BooleanField()),
                        (
                            "registration_end",
                            models.DateTimeField(blank=True, null=True),
                        ),
                        ("attending_fees", models.BooleanField()),
                        (
                            "attending_fees_info",
                            models.TextField(blank=True, null=True),
                        ),
                        (
                            "link",
                            outpost.django.typo3.fields.NormalizedURLField(
                                blank=True, null=True
                            ),
                        ),
                        ("dfp_points", models.IntegerField(blank=True, null=True)),
                        (
                            "contact",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        (
                            "email",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        ("last_modified", models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "typo3_event",
                        "ordering": ("-start", "-end"),
                        "get_latest_by": "start",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE VIEW public.typo3_eventcategory AS SELECT
                            CONCAT(COALESCE(cr.uid_local, ''), COALESCE('-', ''), COALESCE(cr.uid_foreign, '')) AS id,
                            cr.uid_local AS category_id,
                            cr.uid_foreign AS event_id
                        FROM
                            typo3.category_record AS cr
                        JOIN
                            typo3.news AS n ON (n.uid = cr.uid_foreign)
                        WHERE
                            (
                                (CAST((cr.tablenames) AS TEXT) = CAST('tx_news_domain_model_news' AS TEXT)) AND
                                (n.datetime <> 0) AND
                                (n.event_end <> 0)
                                AND (n.deleted = 0) AND
                                (n.hidden = 0) AND
                                (n.is_event = 1))
                    """,
                    reverse_sql="""
                        DROP VIEW public.typo3_eventcategory
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="EventCategory",
                    fields=[
                        (
                            "id",
                            models.CharField(
                                max_length=128, primary_key=True, serialize=False
                            ),
                        ),
                    ],
                    options={
                        "db_table": "typo3_eventcategory",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.typo3_eventcontactbox AS
                        SELECT c.uid AS id,
                            n.uid AS event_id,
                            r.uid_local AS media_id,
                            c.header AS title,
                            c.bodytext AS name,
                                CASE btrim(c.subheader, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim(c.subheader, ' '::text)
                                END AS phone,
                                CASE btrim((c.header_link)::text, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim((c.header_link)::text, ' '::text)
                                END AS url,
                                CASE btrim(c.mugce_link_label, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim(c.mugce_link_label, ' '::text)
                                END AS link_label,
                                CASE btrim(c.mugce_subheader, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim(c.mugce_subheader, ' '::text)
                                END AS email,
                                CASE btrim(c.mugce_caption, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim(c.mugce_caption, ' '::text)
                                END AS headline,
                            ARRAY[c.mugce_text_3, c.mugce_text_4] AS address
                        FROM typo3.content c,
                            typo3.file_reference r,
                            typo3.news n
                        WHERE
                            (
                                (c.uid = r.uid_foreign) AND
                                (c.tx_news_related_news = n.uid) AND
                                ((r.tablenames)::text = 'tt_content'::text) AND
                                ((c.ctype)::text = 'mugce_contact'::text) AND
                                ((r.fieldname)::text = ANY (ARRAY['assets'::text, 'image'::text])) AND
                                ((r.table_local)::text = ANY (ARRAY['sys_file'::text, ''::text])) AND
                                (r.deleted = 0) AND
                                (r.hidden = 0) AND
                                (n.datetime <> 0) AND
                                (n.event_end <> 0) AND
                                ((n.starttime = 0) OR((n.starttime)::double precision > date_part('epoch'::text, now()))) AND
                                (
                                    (
                                        CASE n.full_day
                                            WHEN 1 THEN (n.event_end + 86400)
                                            ELSE n.event_end
                                        END
                                    )::double precision > date_part('epoch'::text, now())
                                ) AND
                                (n.deleted = 0) AND
                                (n.hidden = 0) AND
                                (n.t3ver_wsid = 0) AND
                                (n.is_event = 1)
                            )
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.typo3_eventcontactbox
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="EventContactBox",
                    fields=[
                        ("id", models.IntegerField(primary_key=True, serialize=False)),
                        (
                            "title",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        (
                            "name",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        (
                            "phone",
                            phonenumber_field.modelfields.PhoneNumberField(
                                blank=True, max_length=128, null=True, region=None
                            ),
                        ),
                        ("url", models.URLField(blank=True, null=True)),
                        (
                            "link_label",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        (
                            "email",
                            models.EmailField(blank=True, max_length=254, null=True),
                        ),
                        (
                            "headline",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        (
                            "address",
                            django.contrib.postgres.fields.ArrayField(
                                base_field=models.CharField(
                                    blank=True, max_length=256, null=True
                                ),
                                size=None,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "typo3_eventcontactbox",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.typo3_eventgallery AS
                        SELECT r.uid AS id,
                            r.uid_local AS media_id,
                            n.uid AS event_id,
                                CASE btrim((r.title)::text, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim((r.title)::text, ' '::text)
                                END AS title,
                                CASE btrim(r.description, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim(r.description, ' '::text)
                                END AS description,
                                CASE btrim(r.alternative, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim(r.alternative, ' '::text)
                                END AS alternative,
                            r.sorting AS "order"
                        FROM typo3.news n,
                            typo3.file_reference r,
                            typo3.content c
                        WHERE (((c.ctype)::text = 'mugce_gallery'::text) AND (c.tx_news_related_news = n.uid) AND (c.uid = r.uid_foreign) AND ((r.tablenames)::text = 'tt_content'::text) AND ((r.fieldname)::text = ANY (ARRAY['assets'::text, 'image'::text])) AND ((r.table_local)::text = ANY (ARRAY['sys_file'::text, ''::text])) AND (r.deleted = 0) AND (r.hidden = 0) AND (n.datetime <> 0) AND (n.event_end <> 0) AND ((n.starttime = 0) OR ((n.starttime)::double precision > date_part('epoch'::text, now()))) AND ((
                                CASE n.full_day
                                    WHEN 1 THEN (n.event_end + 86400)
                                    ELSE n.event_end
                                END)::double precision > date_part('epoch'::text, now())) AND (n.deleted = 0) AND (n.hidden = 0) AND (n.t3ver_wsid = 0) AND (n.is_event = 1))
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.typo3_eventgallery
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="EventGallery",
                    fields=[
                        ("id", models.IntegerField(primary_key=True, serialize=False)),
                        (
                            "title",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        ("description", models.TextField(blank=True, null=True)),
                        ("alternative", models.TextField(blank=True, null=True)),
                        ("order", models.PositiveIntegerField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "typo3_eventgallery",
                        "ordering": ("-order",),
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.typo3_eventmedia AS
                        SELECT r.uid AS id,
                            r.uid_local AS media_id,
                            n.uid AS event_id,
                                CASE btrim((r.title)::text, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim((r.title)::text, ' '::text)
                                END AS title,
                                CASE btrim(r.description, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim(r.description, ' '::text)
                                END AS description,
                                CASE btrim(r.alternative, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim(r.alternative, ' '::text)
                                END AS alternative,
                            r.sorting AS "order"
                        FROM typo3.news n,
                            typo3.file_reference r,
                            typo3.content c
                        WHERE (((c.ctype)::text <> 'mugce_contact'::text) AND ((c.ctype)::text <> 'mugce_gallery'::text) AND (c.tx_news_related_news = n.uid) AND (c.uid = r.uid_foreign) AND ((r.tablenames)::text = 'tt_content'::text) AND ((r.fieldname)::text = ANY (ARRAY['assets'::text, 'image'::text])) AND ((r.table_local)::text = ANY (ARRAY['sys_file'::text, ''::text])) AND (r.deleted = 0) AND (r.hidden = 0) AND (n.datetime <> 0) AND (n.event_end <> 0) AND ((n.starttime = 0) OR ((n.starttime)::double precision > date_part('epoch'::text, now()))) AND ((
                                CASE n.full_day
                                    WHEN 1 THEN (n.event_end + 86400)
                                    ELSE n.event_end
                                END)::double precision > date_part('epoch'::text, now())) AND (n.deleted = 0) AND (n.hidden = 0) AND (n.t3ver_wsid = 0) AND (n.is_event = 1))
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.typo3_eventmedia
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="EventMedia",
                    fields=[
                        ("id", models.IntegerField(primary_key=True, serialize=False)),
                        (
                            "title",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        ("description", models.TextField(blank=True, null=True)),
                        ("alternative", models.TextField(blank=True, null=True)),
                        ("order", models.PositiveIntegerField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "typo3_eventmedia",
                        "ordering": ("-order",),
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.typo3_event_related_link AS
                        SELECT nl.uid AS id,
                            nl.pid AS source_id,
                                CASE nl.tstamp
                                    WHEN 0 THEN NULL::timestamp with time zone
                                    ELSE to_timestamp((nl.tstamp)::double precision)
                                END AS datetime,
                            nl.parent AS event_id,
                            nl.sorting AS "order",
                            btrim(public.html_unescape((nl.title)::text)) AS title,
                            NULLIF(btrim(public.html_unescape(nl.description)), ''::text) AS description,
                            nl.uri AS url
                        FROM (typo3.news_links nl
                            JOIN typo3.news n ON ((n.uid = nl.parent)))
                        WHERE (((n.starttime = 0) OR ((n.starttime)::double precision < date_part('epoch'::text, now()))) AND ((n.endtime = 0) OR ((n.endtime)::double precision > date_part('epoch'::text, now()))) AND (n.deleted = 0) AND (n.hidden = 0) AND (n.is_event = 1) AND (n.t3ver_wsid = 0) AND (nl.deleted = 0) AND (nl.hidden = 0))
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.typo3_event_related_link
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="EventRelatedLink",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "order",
                            models.PositiveIntegerField(
                                db_index=True, editable=False, verbose_name="order"
                            ),
                        ),
                        ("datetime", models.DateTimeField(blank=True, null=True)),
                        (
                            "title",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        ("description", models.TextField(blank=True, null=True)),
                        (
                            "url",
                            outpost.django.typo3.fields.LinkField(
                                media_model=outpost.django.typo3.models.Media
                            ),
                        ),
                    ],
                    options={
                        "db_table": "typo3_event_related_link",
                        "ordering": ("order",),
                        "abstract": False,
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.typo3_event_related_media AS
                        SELECT fr.uid AS id,
                            fr.pid AS source_id,
                                CASE fr.tstamp
                                    WHEN 0 THEN NULL::timestamp with time zone
                                    ELSE to_timestamp((fr.tstamp)::double precision)
                                END AS datetime,
                            fr.uid_local AS media_id,
                            fr.uid_foreign AS event_id,
                            fr.sorting_foreign AS "order",
                            NULLIF(btrim((fr.title)::text), ''::text) AS title,
                            NULLIF(btrim(fr.description), ''::text) AS description
                        FROM ((typo3.file_reference fr
                            JOIN typo3.news n ON ((fr.uid_foreign = n.uid)))
                            JOIN typo3.file f ON ((f.uid = fr.uid_local)))
                        WHERE (((fr.tablenames)::text = 'tx_news_domain_model_news'::text) AND ((fr.fieldname)::text = 'fal_related_files'::text) AND ((fr.table_local)::text = ANY (ARRAY['sys_file'::text, ''::text])) AND ((n.starttime = 0) OR ((n.starttime)::double precision < date_part('epoch'::text, now()))) AND ((n.endtime = 0) OR ((n.endtime)::double precision > date_part('epoch'::text, now()))) AND (n.deleted = 0) AND (n.hidden = 0) AND (n.is_event = 1) AND (n.t3ver_wsid = 0) AND (f.storage > 0) AND (f.missing = 0))
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.typo3_event_related_media
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="EventRelatedMedia",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "order",
                            models.PositiveIntegerField(
                                db_index=True, editable=False, verbose_name="order"
                            ),
                        ),
                        ("datetime", models.DateTimeField(blank=True, null=True)),
                        (
                            "title",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        ("description", models.TextField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "typo3_event_related_media",
                        "ordering": ("order",),
                        "abstract": False,
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE FOREIGN TABLE typo3."group" (
                            uid integer,
                            pid integer,
                            tstamp bigint,
                            title character varying,
                            hidden smallint,
                            deleted smallint
                        )
                        SERVER typo3
                        OPTIONS (
                            dbname 'typo3-production',
                            table_name 'fe_groups'
                        )
                    """,
                    reverse_sql="""
                        DROP FOREIGN TABLE typo3."group"
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.typo3_group AS
                        SELECT uid AS id,
                            pid AS page,
                                CASE btrim((title)::text, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim((title)::text, ' '::text)
                                END AS title
                        FROM typo3."group" g
                        WHERE ((hidden = 0) AND (deleted = 0))
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.typo3_group
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Group",
                    fields=[
                        ("id", models.IntegerField(primary_key=True, serialize=False)),
                        (
                            "title",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                    ],
                    options={
                        "db_table": "typo3_group",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.typo3_media AS
                        SELECT uid AS id,
                            storage AS storage_id,
                            identifier AS path,
                            mime_type AS mimetype,
                            name AS filename,
                            size
                        FROM typo3.file f
                        WHERE ((storage > 0) AND (missing = 0))
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.typo3_media
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Media",
                    fields=[
                        ("id", models.IntegerField(primary_key=True, serialize=False)),
                        ("path", models.TextField()),
                        (
                            "mimetype",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        (
                            "filename",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        ("size", models.PositiveIntegerField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "typo3_media",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.typo3_news AS
                        SELECT uid AS id,
                            pid AS source_id,
                                CASE datetime
                                    WHEN 0 THEN NULL::timestamp with time zone
                                    ELSE to_timestamp((datetime)::double precision)
                                END AS datetime,
                            public.html_unescape(title) AS title,
                            public.html_unescape(teaser) AS teaser,
                            public.html_unescape(bodytext) AS body,
                                CASE starttime
                                    WHEN 0 THEN NULL::timestamp with time zone
                                    ELSE to_timestamp((starttime)::double precision)
                                END AS start,
                                CASE endtime
                                    WHEN 0 THEN NULL::timestamp with time zone
                                    ELSE to_timestamp((endtime)::double precision)
                                END AS "end",
                            NULLIF(btrim(author, ' '::text), ''::text) AS author,
                            NULLIF(btrim(author_email, ' '::text), ''::text) AS email,
                            regexp_split_to_array(NULLIF(btrim(keywords), ''::text), '\s*,\s*'::text) AS keywords,
                            NULLIF(btrim(description), ''::text) AS description,
                            tags,
                            (istopnews = 1) AS topnews,
                            to_timestamp((tstamp)::double precision) AS last_modified,
                            ( SELECT fr.uid_local
                                FROM typo3.file_reference fr
                                WHERE ((fr.uid_foreign = n.uid) AND ((fr.tablenames)::text = 'tx_news_domain_model_news'::text) AND ((fr.fieldname)::text = 'fal_media'::text) AND (fr.hidden = 0) AND (fr.deleted = 0) AND (fr.showinpreview = 1))
                                LIMIT 1) AS header_image_id
                        FROM typo3.news n
                        WHERE (((starttime = 0) OR ((starttime)::double precision < date_part('epoch'::text, now()))) AND ((endtime = 0) OR ((endtime)::double precision > date_part('epoch'::text, now()))) AND (deleted = 0) AND (hidden = 0) AND (is_event = 0) AND (t3ver_wsid = 0))
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.typo3_news
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="News",
                    fields=[
                        ("id", models.IntegerField(primary_key=True, serialize=False)),
                        ("datetime", models.DateTimeField(blank=True, null=True)),
                        ("title", models.TextField(blank=True, null=True)),
                        ("teaser", models.TextField(blank=True, null=True)),
                        (
                            "body",
                            outpost.django.typo3.fields.RichTextField(
                                blank=True,
                                media_model=outpost.django.typo3.models.Media,
                                null=True,
                            ),
                        ),
                        ("start", models.DateTimeField(blank=True, null=True)),
                        ("end", models.DateTimeField(blank=True, null=True)),
                        ("author", models.TextField(blank=True, null=True)),
                        ("email", models.TextField(blank=True, null=True)),
                        (
                            "keywords",
                            django.contrib.postgres.fields.ArrayField(
                                base_field=models.TextField(blank=True), size=None
                            ),
                        ),
                        ("description", models.TextField(blank=True, null=True)),
                        ("tags", models.IntegerField(blank=True, null=True)),
                        ("topnews", models.BooleanField()),
                        ("last_modified", models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "typo3_news",
                        "ordering": ("-datetime",),
                        "get_latest_by": "datetime",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE VIEW public.typo3_newscategory AS SELECT CONCAT(COALESCE(cr.uid_local, ''), COALESCE('-', ''), COALESCE(cr.uid_foreign, '')) AS id, cr.uid_local AS category_id, cr.uid_foreign AS news_id FROM (typo3.category_record AS cr JOIN typo3.news AS n ON ((n.uid = cr.uid_foreign))) WHERE ((CAST((cr.tablenames) AS TEXT) = CAST('tx_news_domain_model_news' AS TEXT)) AND ((n.starttime = 0) OR (UNIX_TO_TIME(CAST((n.starttime) AS DOUBLE)) < CURRENT_TIMESTAMP())) AND ((n.endtime = 0) OR (UNIX_TO_TIME(CAST((n.endtime) AS DOUBLE)) > CURRENT_TIMESTAMP())) AND (n.deleted = 0) AND (n.hidden = 0) AND (n.is_event = 0))
                    """,
                    reverse_sql="""
                        DROP VIEW public.typo3_newscategory
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="NewsCategory",
                    fields=[
                        (
                            "id",
                            models.CharField(
                                max_length=128, primary_key=True, serialize=False
                            ),
                        ),
                    ],
                    options={
                        "db_table": "typo3_newscategory",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.typo3_newscontactbox AS
                        SELECT c.uid AS id,
                            n.uid AS news_id,
                            r.uid_local AS media_id,
                            c.header AS title,
                            c.bodytext AS name,
                                CASE btrim(c.subheader, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim(c.subheader, ' '::text)
                                END AS phone,
                                CASE btrim((c.header_link)::text, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim((c.header_link)::text, ' '::text)
                                END AS url,
                                CASE btrim(c.mugce_link_label, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim(c.mugce_link_label, ' '::text)
                                END AS link_label,
                                CASE btrim(c.mugce_subheader, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim(c.mugce_subheader, ' '::text)
                                END AS email,
                                CASE btrim(c.mugce_caption, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim(c.mugce_caption, ' '::text)
                                END AS headline,
                            ARRAY[c.mugce_text_3, c.mugce_text_4] AS address
                        FROM ((typo3.news n
                            JOIN typo3.content c ON (((c.tx_news_related_news = n.uid) AND ((c.ctype)::text = 'mugce_contact'::text))))
                            LEFT JOIN typo3.file_reference r ON ((((r.tablenames)::text = 'tt_content'::text) AND (r.deleted = 0) AND (r.hidden = 0) AND (c.uid = r.uid_foreign) AND ((r.table_local)::text = ANY (ARRAY['sys_file'::text, ''::text])) AND ((r.fieldname)::text = ANY (ARRAY['assets'::text, 'image'::text])))))
                        WHERE ((n.t3ver_wsid = 0) AND (n.is_event = 0))
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.typo3_newscontactbox
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="NewsContactBox",
                    fields=[
                        ("id", models.IntegerField(primary_key=True, serialize=False)),
                        (
                            "title",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        (
                            "name",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        (
                            "phone",
                            phonenumber_field.modelfields.PhoneNumberField(
                                blank=True, max_length=128, null=True, region=None
                            ),
                        ),
                        ("url", models.URLField(blank=True, null=True)),
                        (
                            "link_label",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        (
                            "email",
                            models.EmailField(blank=True, max_length=254, null=True),
                        ),
                        (
                            "headline",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        (
                            "address",
                            django.contrib.postgres.fields.ArrayField(
                                base_field=models.CharField(
                                    blank=True, max_length=256, null=True
                                ),
                                size=None,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "typo3_newscontactbox",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.typo3_newsgallery AS
                        SELECT r.uid AS id,
                            r.uid_local AS media_id,
                            n.uid AS news_id,
                                CASE btrim((r.title)::text, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim((r.title)::text, ' '::text)
                                END AS title,
                                CASE btrim(r.description, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim(r.description, ' '::text)
                                END AS description,
                                CASE btrim(r.alternative, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim(r.alternative, ' '::text)
                                END AS alternative,
                            r.sorting AS "order"
                        FROM typo3.news n,
                            typo3.file_reference r,
                            typo3.content c
                        WHERE (((c.ctype)::text = 'mugce_gallery'::text) AND (c.tx_news_related_news = n.uid) AND (c.uid = r.uid_foreign) AND ((r.tablenames)::text = 'tt_content'::text) AND ((r.fieldname)::text = ANY (ARRAY['assets'::text, 'image'::text])) AND ((r.table_local)::text = ANY (ARRAY['sys_file'::text, ''::text])) AND (r.deleted = 0) AND (r.hidden = 0) AND ((n.starttime = 0) OR ((n.starttime)::double precision < date_part('epoch'::text, now()))) AND ((n.endtime = 0) OR ((n.endtime)::double precision > date_part('epoch'::text, now()))) AND (n.deleted = 0) AND (n.hidden = 0) AND (n.t3ver_wsid = 0) AND (n.is_event = 0))
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.typo3_newsgallery
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="NewsGallery",
                    fields=[
                        ("id", models.IntegerField(primary_key=True, serialize=False)),
                        (
                            "title",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        ("description", models.TextField(blank=True, null=True)),
                        ("alternative", models.TextField(blank=True, null=True)),
                        ("order", models.PositiveIntegerField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "typo3_newsgallery",
                        "ordering": ("-order",),
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.typo3_newsmedia AS
                        SELECT r.uid AS id,
                            r.uid_local AS media_id,
                            n.uid AS news_id,
                                CASE btrim((r.title)::text, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim((r.title)::text, ' '::text)
                                END AS title,
                                CASE btrim(r.description, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim(r.description, ' '::text)
                                END AS description,
                                CASE btrim(r.alternative, ' '::text)
                                    WHEN ''::text THEN NULL::text
                                    ELSE btrim(r.alternative, ' '::text)
                                END AS alternative,
                            r.sorting AS "order"
                        FROM typo3.news n,
                            typo3.file_reference r,
                            typo3.content c
                        WHERE (((c.ctype)::text <> 'mugce_contact'::text) AND ((c.ctype)::text <> 'mugce_gallery'::text) AND (c.tx_news_related_news = n.uid) AND (c.uid = r.uid_foreign) AND ((r.tablenames)::text = 'tt_content'::text) AND ((r.fieldname)::text = ANY (ARRAY['assets'::text, 'image'::text])) AND ((r.table_local)::text = ANY (ARRAY['sys_file'::text, ''::text])) AND (r.deleted = 0) AND (r.hidden = 0) AND ((n.starttime = 0) OR ((n.starttime)::double precision < date_part('epoch'::text, now()))) AND ((n.endtime = 0) OR ((n.endtime)::double precision > date_part('epoch'::text, now()))) AND (n.deleted = 0) AND (n.hidden = 0) AND (n.t3ver_wsid = 0) AND (n.is_event = 0))
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.typo3_newsmedia
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="NewsMedia",
                    fields=[
                        ("id", models.IntegerField(primary_key=True, serialize=False)),
                        (
                            "title",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        ("description", models.TextField(blank=True, null=True)),
                        ("alternative", models.TextField(blank=True, null=True)),
                        ("order", models.PositiveIntegerField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "typo3_newsmedia",
                        "ordering": ("-order",),
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.typo3_news_related_link AS
                        SELECT nl.uid AS id,
                            nl.pid AS source_id,
                                CASE nl.tstamp
                                    WHEN 0 THEN NULL::timestamp with time zone
                                    ELSE to_timestamp((nl.tstamp)::double precision)
                                END AS datetime,
                            nl.parent AS news_id,
                            nl.sorting AS "order",
                            btrim(public.html_unescape((nl.title)::text)) AS title,
                            NULLIF(btrim(public.html_unescape(nl.description)), ''::text) AS description,
                            nl.uri AS url
                        FROM (typo3.news_links nl
                            JOIN typo3.news n ON ((n.uid = nl.parent)))
                        WHERE (((n.starttime = 0) OR ((n.starttime)::double precision < date_part('epoch'::text, now()))) AND ((n.endtime = 0) OR ((n.endtime)::double precision > date_part('epoch'::text, now()))) AND (n.deleted = 0) AND (n.hidden = 0) AND (n.is_event = 0) AND (n.t3ver_wsid = 0) AND (nl.deleted = 0) AND (nl.hidden = 0))
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.typo3_news_related_link
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="NewsRelatedLink",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "order",
                            models.PositiveIntegerField(
                                db_index=True, editable=False, verbose_name="order"
                            ),
                        ),
                        ("datetime", models.DateTimeField(blank=True, null=True)),
                        (
                            "title",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        ("description", models.TextField(blank=True, null=True)),
                        (
                            "url",
                            outpost.django.typo3.fields.LinkField(
                                media_model=outpost.django.typo3.models.Media
                            ),
                        ),
                    ],
                    options={
                        "db_table": "typo3_news_related_link",
                        "ordering": ("order",),
                        "abstract": False,
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.typo3_news_related_media AS
                        SELECT fr.uid AS id,
                            fr.pid AS source_id,
                                CASE fr.tstamp
                                    WHEN 0 THEN NULL::timestamp with time zone
                                    ELSE to_timestamp((fr.tstamp)::double precision)
                                END AS datetime,
                            fr.uid_local AS media_id,
                            fr.uid_foreign AS news_id,
                            fr.sorting_foreign AS "order",
                            NULLIF(btrim((fr.title)::text), ''::text) AS title,
                            NULLIF(btrim(fr.description), ''::text) AS description
                        FROM ((typo3.file_reference fr
                            JOIN typo3.news n ON ((fr.uid_foreign = n.uid)))
                            JOIN typo3.file f ON ((f.uid = fr.uid_local)))
                        WHERE (((fr.tablenames)::text = 'tx_news_domain_model_news'::text) AND ((fr.fieldname)::text = 'fal_related_files'::text) AND ((fr.table_local)::text = ANY (ARRAY['sys_file'::text, ''::text])) AND ((n.starttime = 0) OR ((n.starttime)::double precision < date_part('epoch'::text, now()))) AND ((n.endtime = 0) OR ((n.endtime)::double precision > date_part('epoch'::text, now()))) AND (n.deleted = 0) AND (n.hidden = 0) AND (n.is_event = 0) AND (n.t3ver_wsid = 0) AND (f.storage > 0) AND (f.missing = 0))
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.typo3_news_related_media
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="NewsRelatedMedia",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "order",
                            models.PositiveIntegerField(
                                db_index=True, editable=False, verbose_name="order"
                            ),
                        ),
                        ("datetime", models.DateTimeField(blank=True, null=True)),
                        (
                            "title",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        ("description", models.TextField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "typo3_news_related_media",
                        "ordering": ("order",),
                        "abstract": False,
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW typo3.source AS
                        SELECT uid AS id,
                            title
                        FROM typo3.page p
                        WHERE ((deleted = 0) AND (hidden = 0) AND (( SELECT count(1) AS count
                                FROM typo3.news n
                                WHERE (n.pid = p.uid)) > 0))
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW typo3.source
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE VIEW public.typo3_source AS SELECT s.id, s.title, COALESCE(ds.private, FALSE) AS private FROM (typo3.source AS s LEFT JOIN public.typo3_djangosource AS ds ON ((s.id = ds.id_id)))
                    """,
                    reverse_sql="""
                        DROP VIEW public.typo3_source
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Source",
                    fields=[
                        (
                            "id",
                            models.PositiveIntegerField(
                                primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "title",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        ("private", models.BooleanField()),
                    ],
                    options={
                        "db_table": "typo3_source",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE FOREIGN TABLE typo3.file_storage (
                            uid integer,
                            pid integer,
                            tstamp bigint,
                            crdate bigint,
                            deleted smallint,
                            name text,
                            is_browsable smallint,
                            is_public smallint,
                            is_online smallint,
                            is_default smallint
                        )
                        SERVER typo3
                        OPTIONS (
                            dbname 'typo3-production',
                            table_name 'sys_file_storage'
                        )
                    """,
                    reverse_sql="""
                        DROP FOREIGN TABLE typo3.file_storage
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW typo3.storage AS
                        SELECT uid AS id,
                            name AS title,
                            (is_default = 1) AS "default"
                        FROM typo3.file_storage fs
                        WHERE ((deleted = 0) AND (is_public = 1) AND (is_online = 1))
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW typo3.storage
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE VIEW public.typo3_storage AS SELECT s.id, s.title, ds.url FROM (typo3.storage AS s LEFT JOIN public.typo3_djangostorage AS ds ON ((ds.id_id = s.id)))
                    """,
                    reverse_sql="""
                        DROP VIEW public.typo3_storage
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Storage",
                    fields=[
                        (
                            "id",
                            models.PositiveIntegerField(
                                primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "title",
                            models.CharField(blank=True, max_length=256, null=True),
                        ),
                        ("url", models.URLField()),
                    ],
                    options={
                        "db_table": "typo3_storage",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE FOREIGN TABLE typo3.zmf_course (
                            uid integer,
                            pid integer,
                            tstamp bigint,
                            crdate bigint,
                            sorting integer,
                            deleted smallint,
                            hidden smallint,
                            l10n_parent integer,
                            title character varying,
                            bodytext character varying,
                            email character varying,
                            module integer,
                            categories integer
                        )
                        SERVER typo3
                        OPTIONS (
                            dbname 'typo3-production',
                            table_name 'tx_mugzmfcourses_domain_model_course'
                        )
                    """,
                    reverse_sql="""
                        DROP FOREIGN TABLE typo3.zmf_course
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE VIEW public.typo3_zmf_course AS SELECT
                            uid AS id,
                            pid AS page,
                            UNIX_TO_TIME(CAST((tstamp) AS DOUBLE)) AS last_modified,
                            UNIX_TO_TIME(CAST((crdate) AS DOUBLE)) AS created,
                            sorting,
                            title,
                            NULLIF(CAST((bodytext) AS TEXT), CAST('' AS TEXT)) AS description,
                            email,
                            NULLIF(module, 0) AS module_id,
                            categories AS category_id
                        FROM
                            typo3.zmf_course AS zc
                        WHERE
                            ((deleted = 0) AND (hidden = 0))
                    """,
                    reverse_sql="""
                        DROP VIEW public.typo3_zmf_course
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ZMFCourse",
                    fields=[
                        ("id", models.IntegerField(primary_key=True, serialize=False)),
                        ("page", models.IntegerField()),
                        ("last_modified", models.DateTimeField(blank=True, null=True)),
                        ("created", models.DateTimeField(blank=True, null=True)),
                        ("title", models.TextField(blank=True, null=True)),
                        ("description", models.TextField(blank=True, null=True)),
                        (
                            "email",
                            models.EmailField(blank=True, max_length=254, null=True),
                        ),
                    ],
                    options={
                        "db_table": "typo3_zmf_course",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.CreateModel(
            name="DjangoSource",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="typo3.source",
                    ),
                ),
                ("private", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DjangoStorage",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="typo3.storage",
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
    ]
