# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-16 15:49
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    ops = [
        (
            """
            CREATE SCHEMA typo3;
            """,
            """
            DROP SCHEMA typo3;
            """,
        ),
        (
            """
            CREATE FOREIGN TABLE "typo3"."language" (
                uid int,
                tstamp bigint,
                hidden smallint,
                title varchar,
                flag varchar,
                language_isocode varchar
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'sys_language',
                db_url '{}'
            );
            """.format(
                settings.MULTICORN.get("typo3")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "typo3"."language";
            """,
        ),
        (
            """
            CREATE FOREIGN TABLE "typo3"."category" (
                uid int,
                tstamp bigint,
                crdate bigint,
                deleted smallint,
                hidden smallint,
                starttime bigint,
                endtime bigint,
                sys_language_uid int,
                title text,
                description text,
                parent int,
                items int,
                images int,
                shortcut int,
                tx_odsosm_marker int,
                slug varchar
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'sys_category',
                db_url '{}'
            );
            """.format(
                settings.MULTICORN.get("typo3")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "typo3"."category";
            """,
        ),
        (
            """
            CREATE FOREIGN TABLE "typo3"."news" (
                uid int,
                pid int,
                tstamp bigint,
                crdate bigint,
                sys_language_uid int,
                deleted smallint,
                hidden smallint,
                starttime bigint,
                endtime bigint,
                sorting int,
                fe_group varchar,
                title text,
                teaser text,
                bodytext text,
                datetime bigint,
                archive bigint,
                author text,
                author_email text,
                categories int,
                related int,
                related_from int,
                related_files text,
                related_links text,
                type varchar,
                keywords text,
                tags int,
                media text,
                internalurl text,
                externalurl text,
                istopnews integer,
                content_elements text,
                path_segment text,
                alternative_title text,
                description text,
                fal_related_files int,
                fal_media int,
                is_event smallint,
                full_day smallint,
                event_end int,
                organizer int,
                location int,
                organizer_simple varchar,
                location_simple varchar,
                www varchar,
                contact_name varchar,
                contact_email varchar,
                register smallint,
                registration_end int,
                attendingfees smallint,
                dfppoints int
            )
            SERVER sqlalchemy
            OPTIONS (
                tablename 'tx_news_domain_model_news',
                db_url '{}'
            );
            """.format(
                settings.MULTICORN.get("typo3")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "typo3"."news";
            """,
        ),
        (
            """
            CREATE FOREIGN TABLE "typo3"."category_record" (
                uid_local int,
                uid_foreign int,
                tablenames varchar,
                sorting int,
                sorting_foreign int,
                fieldname varchar
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'sys_category_record_mm',
                db_url '{}'
            );
            """.format(
                settings.MULTICORN.get("typo3")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "typo3"."category_record";
            """,
        ),
        (
            """
            CREATE FOREIGN TABLE "typo3"."file" (
                uid int,
                pid int,
                tstamp bigint,
                type varchar,
                storage int,
                identifier text,
                extension varchar,
                mime_type varchar,
                name text,
                sha1 varchar,
                size bigint,
                creation_date bigint,
                modification_date bigint,
                last_indexed bigint,
                missing smallint,
                metadata int,
                identifier_hash varchar,
                folder_hash varchar
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'sys_file',
                db_url '{typo3}'
            );
            """.format(
                typo3=settings.MULTICORN.get("typo3")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "typo3"."file";
            """,
        ),
        (
            """
            CREATE FOREIGN TABLE "typo3"."file_reference" (
                uid int,
                pid int,
                tstamp bigint,
                crdate bigint,
                cruser_id int,
                sorting int,
                deleted smallint,
                hidden smallint,
                sys_language_uid int,
                uid_local int,
                uid_foreign int,
                tablenames varchar,
                fieldname varchar,
                sorting_foreign int,
                table_local varchar,
                title varchar,
                description text,
                alternative text,
                link varchar,
                downloadname text,
                showinpreview smallint,
                crop text,
                autoplay smallint
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'sys_file_reference',
                db_url '{typo3}'
            );
            """.format(
                typo3=settings.MULTICORN.get("typo3")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "typo3"."file_reference";
            """,
        ),
        (
            """
            CREATE FOREIGN TABLE "typo3"."group" (
                uid int,
                pid int,
                tstamp bigint,
                title varchar,
                hidden smallint,
                deleted smallint
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'fe_groups',
                db_url '{typo3}'
            );
            """.format(
                typo3=settings.MULTICORN.get("typo3")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "typo3"."group";
            """,
        ),
        (
            """
            CREATE FOREIGN TABLE "typo3"."page" (
                uid int,
                pid int,
                tstamp bigint,
                crdate bigint,
                deleted smallint,
                hidden smallint,
                title text
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'pages',
                db_url '{}'
            );
            """.format(
                settings.MULTICORN.get("typo3")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "typo3"."page";
            """,
        ),
        (
            """
            CREATE FOREIGN TABLE "typo3"."file_storage" (
                uid int,
                pid int,
                tstamp bigint,
                crdate bigint,
                deleted smallint,
                name text,
                is_browsable smallint,
                is_public smallint,
                is_online smallint,
                is_default smallint
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'sys_file_storage',
                db_url '{}'
            );
            """.format(
                settings.MULTICORN.get("typo3")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "typo3"."file_storage";
            """,
        ),
        (
            """
            CREATE FOREIGN TABLE "typo3"."zmf_course" (
                uid int,
                pid int,
                tstamp bigint,
                crdate bigint,
                sorting int,
                deleted smallint,
                hidden smallint,
                sys_language_uid int,
                l10n_parent int,
                title varchar,
                bodytext varchar,
                email varchar,
                module int,
                categories int
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'tx_mugzmfcourses_domain_model_course',
                db_url '{}'
            );
            """.format(
                settings.MULTICORN.get("typo3")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "typo3"."zmf_course";
            """,
        ),
    ]
    dependencies = [("typo3", "0001_initial")]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
