# Generated by Django 5.2.16 on 2026-08-13 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("typo3", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ZMFCourse",
        ),
    ]
