# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-16 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    ops = [
        (
            """
            CREATE VIEW "public"."typo3_language" AS SELECT
                uid AS id,
                title,
                flag,
                language_isocode AS isocode
            FROM
                "typo3"."language"
            WHERE
                hidden = 0;
            """,
            """
            DROP VIEW IF EXISTS "public"."typo3_language";
            """,
        ),
        (
            """
            CREATE VIEW "public"."typo3_category" AS SELECT
                uid AS id,
                CASE WHEN
                    sys_language_uid > 0
                THEN
                    sys_language_uid
                ELSE
                    NULL
                END AS language_id,
                CASE
                    starttime
                WHEN
                    0
                THEN
                    NULL
                ELSE
                    to_timestamp(starttime)
                END AS start,
                CASE
                    endtime
                WHEN
                    0
                THEN
                    NULL
                ELSE
                    to_timestamp(endtime)
                END AS end,
                title,
                description,
                parent,
                tx_odsosm_marker AS marker
            FROM "typo3"."category"
            WHERE
                deleted = 0 AND
                hidden = 0;
            """,
            """
            DROP VIEW IF EXISTS "public"."typo3_category";
            """,
        ),
        (
            """

            CREATE MATERIALIZED VIEW "public"."typo3_group" AS
            SELECT
                g.uid AS id,
                g.pid AS page,
                CASE btrim(g.title, ' ')
                WHEN
                    ''
                THEN
                    NULL
                ELSE
                    btrim(g.title, ' ')
                END AS title
            FROM
                typo3."group" g
            WHERE
                g.hidden = 0
                AND
                g.deleted = 0
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_group";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "typo3"."source" AS
            SELECT
                p.uid AS id,
                p.title
            FROM
                "typo3"."page" p
            WHERE
                p.deleted = 0
                AND
                p.hidden = 0
                AND
                (SELECT COUNT(1) FROM "typo3"."news" AS n WHERE n.pid = p.uid) > 0
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "typo3"."source";
            """,
        ),
        (
            """
            CREATE VIEW "public"."typo3_source" AS
            SELECT
                s.id AS id,
                s.title AS title,
                COALESCE(ds.private, FALSE) AS private
            FROM
                "typo3"."source" AS s
            LEFT OUTER JOIN
                "public"."typo3_djangosource" AS ds ON (s.id = ds.id_id)
            """,
            """
            DROP VIEW IF EXISTS "public"."typo3_source";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "typo3"."storage" AS
            SELECT
                fs.uid AS id,
                fs.name AS title,
                fs.is_default = 1 AS default
            FROM
                "typo3"."file_storage" AS fs
            WHERE
                fs.deleted = 0
                AND
                fs.is_public = 1
                AND
                fs.is_online = 1
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "typo3"."storage";
            """,
        ),
        (
            """
            CREATE VIEW "public"."typo3_storage" AS
            SELECT
                s.id AS id,
                s.title AS title,
                ds.url AS url
            FROM
                "typo3"."storage" AS s
            LEFT JOIN
                "public"."typo3_djangostorage" AS ds ON (ds.id_id = s.id)
            """,
            """
            DROP VIEW IF EXISTS "public"."typo3_storage";
            """,
        ),
        (
            """
            CREATE VIEW "public"."typo3_zmf_course" AS
            SELECT
                zc.uid AS id,
                zc.pid AS page,
                to_timestamp(zc.tstamp) AS last_modified,
                to_timestamp(zc.crdate) AS created,
                zc.sorting AS sorting,
                CASE WHEN
                    zc.sys_language_uid > 0
                THEN
                    zc.sys_language_uid
                ELSE
                    NULL
                END AS language_id,
                CASE WHEN
                    zc.sys_language_uid > 0
                THEN
                    zc.l10n_parent
                ELSE
                    NULL
                END AS language_parent_id,
                zc.title AS title,
                NULLIF(zc.bodytext, '') AS description,
                zc.email AS email,
                NULLIF(zc.module, 0) AS module_id,
                zc.categories AS category_id
            FROM
                "typo3"."zmf_course" AS zc
            WHERE
                zc.deleted = 0
                AND
                zc.hidden = 0
            """,
            """
            DROP VIEW IF EXISTS "public"."typo3_zmf_course";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_media" AS SELECT
                f.uid AS id,
                f.storage AS storage_id,
                f.identifier AS path,
                f.mime_type AS mimetype,
                f.name AS filename,
                f.size::bigint AS size
            FROM
                typo3.file AS f
            WHERE
                storage > 0
                AND
                missing = 0
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_media";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_news" AS
            SELECT
                n.uid AS id,
                n.pid AS source_id,
                CASE WHEN
                    n.sys_language_uid > 0
                THEN
                    n.sys_language_uid
                ELSE
                    NULL::integer
                END AS language_id,
                CASE
                    n.datetime
                WHEN
                    0
                THEN
                    NULL::timestamp WITH time ZONE
                ELSE
                    to_timestamp(n.datetime)
                END AS datetime,
                html_unescape(n.title) AS title,
                html_unescape(n.teaser) AS teaser,
                html_unescape(n.bodytext) AS body,
                CASE
                    n.starttime
                WHEN
                    0
                THEN
                    NULL::timestamp WITH time ZONE
                ELSE
                    to_timestamp(n.starttime)
                END AS START,
                CASE
                    n.endtime
                WHEN
                    0
                THEN
                    NULL::timestamp WITH time ZONE
                ELSE
                    to_timestamp(n.endtime)
                END AS "end",
                NULLIF(BTRIM(n.author, ' '), '') AS author,
                NULLIF(BTRIM(n.author_email, ' '), '') AS email,
                NULLIF(BTRIM(n.keywords, ' '), '') AS keywords,
                n.tags AS tags,
                n.istopnews = 1 AS topnews,
                to_timestamp(n.tstamp) AS last_modified
            FROM
                typo3.news AS n
            WHERE
                (
                    n.starttime = 0
                    OR
                    to_timestamp(n.starttime) < now()
                )
                AND
                (
                    n.endtime = 0
                    OR
                    to_timestamp(n.endtime) > now()
                )
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 0
                WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_news";
            """,
        ),
        (
            """
            CREATE UNIQUE INDEX "typo3_news_id_idx" ON public.typo3_news USING btree (id);
            """,
            """
            DROP INDEX IF EXISTS "typo3_news_id_idx";
            """,
        ),
        (
            """
            CREATE VIEW "public"."typo3_newscategory" AS
            SELECT
                concat(cr.uid_local, '-', cr.uid_foreign) AS id,
                cr.uid_local AS category_id,
                cr.uid_foreign AS news_id
            FROM
                typo3.category_record cr
            JOIN
                typo3.news n ON (n.uid = cr.uid_foreign)
            WHERE
                cr.tablenames = 'tx_news_domain_model_news'
                AND
                (
                    n.starttime = 0
                    OR
                    to_timestamp(n.starttime) < now()
                )
                AND
                (
                    n.endtime = 0
                    OR
                    to_timestamp(n.endtime) > now()
                )
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 0
            """,
            """
            DROP VIEW IF EXISTS "public"."typo3_newscategory";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_news_group" AS SELECT
                n.uid AS news_id,
                unnest(string_to_array(n.fe_group, ',')::integer[]) AS group_id
            FROM
                typo3.news AS n
            WHERE
                n.fe_group IS NOT NULL
                AND
                (
                    n.starttime = 0
                    OR
                    to_timestamp(n.starttime) < now()
                )
                AND
                (
                    n.endtime = 0
                    OR
                    to_timestamp(n.endtime) > now()
                )
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 0
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_news_group";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_newsmedia" AS
            SELECT
                r.uid AS id,
                r.uid_local AS media_id,
                r.uid_foreign AS news_id,
                CASE
                    btrim(r.title, ' ')
                WHEN
                    ''
                THEN
                    NULL
                ELSE
                    btrim(r.title, ' ')
                END AS title,
                CASE
                    btrim(r.description, ' ')
                WHEN
                    ''
                THEN
                    NULL
                ELSE
                    btrim(r.description, ' ')
                END AS description,
                CASE
                    btrim(r.alternative, ' ')
                WHEN
                    ''
                THEN
                    NULL
                ELSE
                    btrim(r.alternative, ' ')
                END AS alternative,
                CASE WHEN
                    r.sys_language_uid <= 0
                THEN
                    NULL::integer
                ELSE
                    r.sys_language_uid
                END AS language_id,
                r.sorting AS "order",
                r.showinpreview::int::boolean AS preview
            FROM
                typo3.news n,
                typo3.file_reference r
            WHERE
                r.tablenames = 'tx_news_domain_model_news'
                AND
                r.table_local = 'sys_file'
                AND
                (
                    r.fieldname = ANY (ARRAY['fal_media', 'fal_related_files'])
                )
                AND
                r.uid_foreign = n.uid
                AND
                r.deleted = 0
                AND
                r.hidden = 0
                AND
                (
                    n.starttime = 0
                    OR
                    to_timestamp(n.starttime) < now()
                )
                AND
                (
                    n.endtime = 0
                    OR
                    to_timestamp(n.endtime) > now()
                )
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 0
                WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_newsmedia";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_event" AS
            SELECT
                n.uid AS id,
                n.pid AS source_id,
                CASE
                    n.full_day
                WHEN
                    1
                THEN
                    to_timestamp(n.datetime)::date + '00:00:00'::INTERVAL
                ELSE
                    to_timestamp(n.datetime)
                END AS START,
                CASE
                    n.full_day
                WHEN
                    1
                THEN
                    to_timestamp(n.event_end)::date + '24:00:00'::INTERVAL
                ELSE
                    to_timestamp(n.event_end)
                END AS "end",
                n.full_day::int::boolean AS allday,
                html_unescape(n.title) AS title,
                NULLIF(BTRIM(n.organizer_simple, ' '), '') AS organizer,
                NULLIF(BTRIM(n.location_simple, ' '), '') AS location,
                html_unescape(n.teaser) AS teaser,
                html_unescape(n.bodytext) AS body,
                CASE WHEN
                    n.sys_language_uid > 0
                THEN
                    n.sys_language_uid
                ELSE
                    NULL
                END AS language_id,
                n.register::int::boolean AS register,
                CASE WHEN
                    n.registration_end > 0
                THEN
                    to_timestamp(n.registration_end)
                ELSE
                    NULL
                END AS registration_end,
                n.attendingfees::int::boolean AS attending_fees,
                NULLIF(BTRIM(n.www, ' '), '') AS link,
                CASE WHEN
                    n.dfppoints > 0
                THEN
                    n.dfppoints
                ELSE
                    NULL
                END AS dfp_points,
                NULLIF(BTRIM(n.contact_name, ' '), '') AS contact,
                NULLIF(BTRIM(n.contact_email, ' '), '') AS email,
                to_timestamp(n.tstamp) AS last_modified
            FROM
                typo3.news AS n
            WHERE
                n.datetime <> 0
                AND
                n.event_end <> 0
                AND
                (
                    n.starttime = 0
                    OR
                    to_timestamp(n.starttime) > now()
                )
                AND
                (
                    CASE
                        n.full_day
                    WHEN
                        1
                    THEN
                        to_timestamp(n.event_end) + '24:00:00'::INTERVAL
                    ELSE
                        to_timestamp(n.event_end)
                    END
                ) > now()
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 1
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_event";
            """,
        ),
        (
            """
            CREATE UNIQUE INDEX "typo3_event_id_idx" ON "public"."typo3_event" USING btree (id);
            """,
            """
            DROP INDEX IF EXISTS "typo3_event_id_idx";
            """,
        ),
        (
            """
            CREATE VIEW "public"."typo3_eventcategory" AS
            SELECT
                concat(cr.uid_local, '-', cr.uid_foreign) AS id,
                cr.uid_local AS category_id,
                cr.uid_foreign AS event_id
            FROM
                typo3.category_record cr
            JOIN
                typo3.news n ON (n.uid = cr.uid_foreign)
            WHERE
                cr.tablenames = 'tx_news_domain_model_news'
                AND
                n.datetime <> 0
                AND
                n.event_end <> 0
                AND
                (
                    n.starttime = 0
                    OR
                    to_timestamp(n.starttime) > now()
                )
                AND
                (
                    CASE
                        n.full_day
                    WHEN
                        1
                    THEN
                        to_timestamp(n.event_end) + '24:00:00'::INTERVAL
                    ELSE
                        to_timestamp(n.event_end)
                    END
                ) > now()
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 1
            """,
            """
            DROP VIEW IF EXISTS "public"."typo3_eventcategory";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_event_group" AS SELECT
                n.uid AS event_id,
                unnest(string_to_array(n.fe_group, ',')::integer[]) AS group_id
            FROM
                typo3.news AS n
            WHERE
                n.fe_group IS NOT NULL
                AND
                n.datetime <> 0
                AND
                n.event_end <> 0
                AND
                (
                    n.starttime = 0
                    OR
                    to_timestamp(n.starttime) > now()
                )
                AND
                (
                    CASE
                        n.full_day
                    WHEN
                        1
                    THEN
                        to_timestamp(n.event_end) + '24:00:00'::INTERVAL
                    ELSE
                        to_timestamp(n.event_end)
                    END
                ) > now()
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 1
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_event_group";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_eventmedia" AS
            SELECT
                r.uid AS id,
                r.uid_local AS media_id,
                r.uid_foreign AS event_id,
                CASE
                    btrim(r.title, ' ')
                WHEN
                    ''
                THEN
                    NULL
                ELSE
                    btrim(r.title, ' ')
                END AS title,
                CASE
                    btrim(r.description, ' ')
                WHEN
                    ''
                THEN NULL
                ELSE
                    btrim(r.description, ' ')
                END AS description,
                CASE
                    btrim(r.alternative, ' ')
                WHEN
                    ''
                THEN
                    NULL
                ELSE
                    btrim(r.alternative, ' ')
                END AS alternative,
                CASE WHEN
                    r.sys_language_uid <= 0
                THEN
                    NULL
                ELSE
                    r.sys_language_uid
                END AS language_id,
                r.sorting AS "order",
                r.showinpreview::int::boolean AS preview
            FROM
                typo3.news n,
                typo3.file_reference r
            WHERE
                r.tablenames = 'tx_news_domain_model_news'
                AND
                r.table_local = 'sys_file'
                AND
                (
                    r.fieldname = ANY (ARRAY['fal_media', 'fal_related_files'])
                )
                AND
                r.uid_foreign = n.uid
                AND
                r.deleted = 0
                AND
                r.hidden = 0
                AND
                n.datetime <> 0
                AND
                n.event_end <> 0
                AND
                (
                    n.starttime = 0
                    OR
                    to_timestamp(n.starttime) > now()
                )
                AND
                (
                    CASE
                        n.full_day
                    WHEN
                        1
                    THEN
                        to_timestamp(n.event_end) + '24:00:00'::INTERVAL
                    ELSE
                        to_timestamp(n.event_end)
                    END
                ) > now()
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 1
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_eventmedia";
            """,
        ),
    ]

    dependencies = [("typo3", "0002_foreign")]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
