# Generated by Django 5.2.16 on 2026-08-13 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_language"),
        ("typo3", "0002_delete_zmfcourse"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceLanguage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveIntegerField()),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.language"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="typo3.source",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DROP MATERIALIZED VIEW public.typo3_event
                    """,
                    reverse_sql="""
                        CREATE MATERIALIZED VIEW public.typo3_event
                          AS SELECT uid AS id
                                  , pid AS source_id
                                  , to_timestamp(CAST(datetime AS double precision)) AS start
                                  , CASE event_end
                                      WHEN 0
                                        THEN CAST(CAST(to_timestamp(CAST(datetime AS double precision)) AS date) + CAST('24:00:00' AS interval) AS timestamp with time zone)
                                      ELSE to_timestamp(CAST(event_end AS double precision))
                                    END AS "end"
                                  , CAST(CAST(full_day AS integer) AS boolean) AS allday
                                  , public.html_unescape(title) AS title
                                  , NULLIF(btrim(CAST(organizer_simple AS text)
                                               , CAST(' ' AS text))
                                         , CAST('' AS text)) AS organizer
                                  , NULLIF(btrim(CAST(location_simple AS text)
                                               , CAST(' ' AS text))
                                         , CAST('' AS text)) AS location
                                  , public.html_unescape(teaser) AS teaser
                                  , public.html_unescape(bodytext) AS body
                                  , regexp_split_to_array(NULLIF(btrim(keywords)
                                                               , CAST('' AS text))
                                                        , CAST('\s*,\s*' AS text)) AS keywords
                                  , NULLIF(btrim(description)
                                         , CAST('' AS text)) AS description
                                  , CAST(CAST(register AS integer) AS boolean) AS register
                                  , CASE
                                      WHEN registration_end > 0
                                        THEN to_timestamp(CAST(registration_end AS double precision))
                                      ELSE CAST(NULL AS timestamp with time zone)
                                    END AS registration_end
                                  , CAST(CAST(attendingfees AS integer) AS boolean) AS attending_fees
                                  , NULLIF(btrim(attendingfees_info)
                                         , CAST('' AS text)) AS attending_fees_info
                                  , NULLIF(btrim(CAST(www AS text)
                                               , CAST(' ' AS text))
                                         , CAST('' AS text)) AS link
                                  , CASE
                                      WHEN dfppoints > 0
                                        THEN dfppoints
                                      ELSE CAST(NULL AS integer)
                                    END AS dfp_points
                                  , NULLIF(btrim(CAST(contact_name AS text)
                                               , CAST(' ' AS text))
                                         , CAST('' AS text)) AS contact
                                  , NULLIF(btrim(CAST(contact_email AS text)
                                               , CAST(' ' AS text))
                                         , CAST('' AS text)) AS email
                                  , to_timestamp(CAST(tstamp AS double precision)) AS last_modified
                                  , (SELECT fr.uid_local
                                     FROM typo3.file_reference AS fr
                                     WHERE fr.uid_foreign = n.uid
                                       AND CAST(fr.tablenames AS text) = CAST('tx_news_domain_model_news' AS text)
                                       AND CAST(fr.fieldname AS text) = CAST('fal_media' AS text)
                                       AND fr.showinpreview = 1
                                       AND fr.hidden = 0
                                       AND fr.deleted = 0
                                     ORDER BY fr.sorting
                                     LIMIT 1) AS header_image_id
                             FROM typo3.news AS n
                             WHERE datetime <> 0
                               AND deleted = 0
                               AND hidden = 0
                               AND t3ver_wsid = 0
                               AND is_event = 1
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.typo3_event
                          AS SELECT uid AS id
                                  , pid AS source_id
                                  , to_timestamp(CAST(datetime AS double precision)) AS start
                                  , CASE event_end
                                      WHEN 0
                                        THEN CAST(CAST(to_timestamp(CAST(datetime AS double precision)) AS date) + CAST('24:00:00' AS interval) AS timestamp with time zone)
                                      ELSE to_timestamp(CAST(event_end AS double precision))
                                    END AS "end"
                                  , CAST(CAST(full_day AS integer) AS boolean) AS allday
                                  , public.html_unescape(title) AS title
                                  , NULLIF(btrim(CAST(organizer_simple AS text)
                                               , CAST(' ' AS text))
                                         , CAST('' AS text)) AS organizer
                                  , NULLIF(btrim(CAST(location_simple AS text)
                                               , CAST(' ' AS text))
                                         , CAST('' AS text)) AS location
                                  , public.html_unescape(teaser) AS teaser
                                  , public.html_unescape(bodytext) AS body
                                  , regexp_split_to_array(NULLIF(btrim(keywords)
                                                               , CAST('' AS text))
                                                        , CAST('\s*,\s*' AS text)) AS keywords
                                  , NULLIF(btrim(description)
                                         , CAST('' AS text)) AS description
                                  , CAST(CAST(register AS integer) AS boolean) AS register
                                  , CASE
                                      WHEN registration_end > 0
                                        THEN to_timestamp(CAST(registration_end AS double precision))
                                      ELSE CAST(NULL AS timestamp with time zone)
                                    END AS registration_end
                                  , CAST(CAST(attendingfees AS integer) AS boolean) AS attending_fees
                                  , NULLIF(btrim(attendingfees_info)
                                         , CAST('' AS text)) AS attending_fees_info
                                  , NULLIF(btrim(CAST(www AS text)
                                               , CAST(' ' AS text))
                                         , CAST('' AS text)) AS link
                                  , CASE
                                      WHEN dfppoints > 0
                                        THEN dfppoints
                                      ELSE CAST(NULL AS integer)
                                    END AS dfp_points
                                  , NULLIF(btrim(CAST(contact_name AS text)
                                               , CAST(' ' AS text))
                                         , CAST('' AS text)) AS contact
                                  , NULLIF(btrim(CAST(contact_email AS text)
                                               , CAST(' ' AS text))
                                         , CAST('' AS text)) AS email
                                  , to_timestamp(CAST(tstamp AS double precision)) AS last_modified
                                  , (SELECT fr.uid_local
                                     FROM typo3.file_reference AS fr
                                     WHERE fr.uid_foreign = n.uid
                                       AND CAST(fr.tablenames AS text) = CAST('tx_news_domain_model_news' AS text)
                                       AND CAST(fr.fieldname AS text) = CAST('fal_media' AS text)
                                       AND fr.showinpreview = 1
                                       AND fr.hidden = 0
                                       AND fr.deleted = 0
                                     ORDER BY fr.sorting
                                     LIMIT 1) AS header_image_id
                                  , CASE
                                      WHEN sys_language_uid > 0
                                        THEN sl.id
                                      ELSE CAST(NULL AS integer)
                                    END AS language_id
                             FROM
                               typo3.news AS n,
                               typo3_sourcelanguage AS sl
                             WHERE n.pid = sl.source_id
                               AND n.sys_language_uid = sl.value
                               AND datetime <> 0
                               AND deleted = 0
                               AND hidden = 0
                               AND t3ver_wsid = 0
                               AND is_event = 1
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.typo3_event
                    """,
                ),
            ],
            state_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DROP MATERIALIZED VIEW public.typo3_news
                    """,
                    reverse_sql="""
                        CREATE MATERIALIZED VIEW public.typo3_news
                          AS SELECT uid AS id
                                  , pid AS source_id
                                  , CASE datetime
                                      WHEN 0
                                        THEN CAST(NULL AS timestamp with time zone)
                                      ELSE to_timestamp(CAST(datetime AS double precision))
                                    END AS datetime
                                  , public.html_unescape(title) AS title
                                  , public.html_unescape(teaser) AS teaser
                                  , public.html_unescape(bodytext) AS body
                                  , CASE starttime
                                      WHEN 0
                                        THEN CAST(NULL AS timestamp with time zone)
                                      ELSE to_timestamp(CAST(starttime AS double precision))
                                    END AS start
                                  , CASE endtime
                                      WHEN 0
                                        THEN CAST(NULL AS timestamp with time zone)
                                      ELSE to_timestamp(CAST(endtime AS double precision))
                                    END AS "end"
                                  , NULLIF(btrim(author
                                               , CAST(' ' AS text))
                                         , CAST('' AS text)) AS author
                                  , NULLIF(btrim(author_email
                                               , CAST(' ' AS text))
                                         , CAST('' AS text)) AS email
                                  , regexp_split_to_array(NULLIF(btrim(keywords)
                                                               , CAST('' AS text))
                                                        , CAST('\s*,\s*' AS text)) AS keywords
                                  , NULLIF(btrim(description)
                                         , CAST('' AS text)) AS description
                                  , tags
                                  , istopnews = 1 AS topnews
                                  , to_timestamp(CAST(tstamp AS double precision)) AS last_modified
                                  , (SELECT fr.uid_local
                                     FROM typo3.file_reference AS fr
                                     WHERE fr.uid_foreign = n.uid
                                       AND CAST(fr.tablenames AS text) = CAST('tx_news_domain_model_news' AS text)
                                       AND CAST(fr.fieldname AS text) = CAST('fal_media' AS text)
                                       AND fr.hidden = 0
                                       AND fr.deleted = 0
                                       AND fr.showinpreview = 1
                                     LIMIT 1) AS header_image_id
                             FROM typo3.news AS n
                             WHERE (starttime = 0
                                 OR CAST(starttime AS double precision) < date_part(CAST('epoch' AS text)
                                                                                  , now()))
                               AND (endtime = 0
                                 OR CAST(endtime AS double precision) > date_part(CAST('epoch' AS text)
                                                                                , now()))
                               AND deleted = 0
                               AND hidden = 0
                               AND is_event = 0
                               AND t3ver_wsid = 0
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.typo3_news
                          AS SELECT uid AS id
                                  , pid AS source_id
                                  , CASE datetime
                                      WHEN 0
                                        THEN CAST(NULL AS timestamp with time zone)
                                      ELSE to_timestamp(CAST(datetime AS double precision))
                                    END AS datetime
                                  , public.html_unescape(title) AS title
                                  , public.html_unescape(teaser) AS teaser
                                  , public.html_unescape(bodytext) AS body
                                  , CASE starttime
                                      WHEN 0
                                        THEN CAST(NULL AS timestamp with time zone)
                                      ELSE to_timestamp(CAST(starttime AS double precision))
                                    END AS start
                                  , CASE endtime
                                      WHEN 0
                                        THEN CAST(NULL AS timestamp with time zone)
                                      ELSE to_timestamp(CAST(endtime AS double precision))
                                    END AS "end"
                                  , NULLIF(btrim(author
                                               , CAST(' ' AS text))
                                         , CAST('' AS text)) AS author
                                  , NULLIF(btrim(author_email
                                               , CAST(' ' AS text))
                                         , CAST('' AS text)) AS email
                                  , regexp_split_to_array(NULLIF(btrim(keywords)
                                                               , CAST('' AS text))
                                                        , CAST('\s*,\s*' AS text)) AS keywords
                                  , NULLIF(btrim(description)
                                         , CAST('' AS text)) AS description
                                  , tags
                                  , istopnews = 1 AS topnews
                                  , to_timestamp(CAST(tstamp AS double precision)) AS last_modified
                                  , (SELECT fr.uid_local
                                     FROM typo3.file_reference AS fr
                                     WHERE fr.uid_foreign = n.uid
                                       AND CAST(fr.tablenames AS text) = CAST('tx_news_domain_model_news' AS text)
                                       AND CAST(fr.fieldname AS text) = CAST('fal_media' AS text)
                                       AND fr.hidden = 0
                                       AND fr.deleted = 0
                                       AND fr.showinpreview = 1
                                     LIMIT 1) AS header_image_id
                                  , CASE
                                      WHEN sys_language_uid > 0
                                        THEN sl.id
                                      ELSE CAST(NULL AS integer)
                                    END AS language_id
                             FROM
                               typo3.news AS n,
                               typo3_sourcelanguage AS sl
                             WHERE n.pid = sl.source_id
                               AND n.sys_language_uid = sl.value
                               AND  (starttime = 0
                                 OR CAST(starttime AS double precision) < date_part(CAST('epoch' AS text)
                                                                                  , now()))
                               AND (endtime = 0
                                 OR CAST(endtime AS double precision) > date_part(CAST('epoch' AS text)
                                                                                , now()))
                               AND deleted = 0
                               AND hidden = 0
                               AND is_event = 0
                               AND t3ver_wsid = 0
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.typo3_news
                    """,
                ),
            ],
            state_operations=[],
        ),
    ]
