# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-22 12:52
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    ops = [
        (
            """
            CREATE FOREIGN TABLE "typo3"."content" (
                uid int,
                pid int,
                tstamp bigint,
                crdate bigint,
                cruser_id int,
                sorting int,
                deleted smallint,
                hidden smallint,
                CType varchar,
                header varchar,
                bodytext text,
                header_link varchar,
                list_type varchar,
                tx_news_related_news int
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'tt_content',
                db_url '{typo3}'
            );
            """.format(
                typo3=settings.MULTICORN.get("typo3")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "typo3"."content";
            """,
        ),
        (
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_newsmedia";
            """,
            """
            CREATE MATERIALIZED VIEW "public"."typo3_newsmedia" AS
            SELECT
                r.uid AS id,
                r.uid_local AS media_id,
                r.uid_foreign AS news_id,
                CASE
                    btrim(r.title, ' ')
                WHEN
                    ''
                THEN
                    NULL
                ELSE
                    btrim(r.title, ' ')
                END AS title,
                CASE
                    btrim(r.description, ' ')
                WHEN
                    ''
                THEN
                    NULL
                ELSE
                    btrim(r.description, ' ')
                END AS description,
                CASE
                    btrim(r.alternative, ' ')
                WHEN
                    ''
                THEN
                    NULL
                ELSE
                    btrim(r.alternative, ' ')
                END AS alternative,
                CASE WHEN
                    r.sys_language_uid <= 0
                THEN
                    NULL::integer
                ELSE
                    r.sys_language_uid
                END AS language_id,
                r.sorting AS "order",
                r.showinpreview::int::boolean AS preview
            FROM
                typo3.news n,
                typo3.file_reference r
            WHERE
                r.tablenames = 'tx_news_domain_model_news'
                AND
                r.table_local = 'sys_file'
                AND
                (
                    r.fieldname = ANY (ARRAY['fal_media', 'fal_related_files'])
                )
                AND
                r.uid_foreign = n.uid
                AND
                r.deleted = 0
                AND
                r.hidden = 0
                AND
                (
                    n.starttime = 0
                    OR
                    to_timestamp(n.starttime) < now()
                )
                AND
                (
                    n.endtime = 0
                    OR
                    to_timestamp(n.endtime) > now()
                )
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 0
                WITH DATA;
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_newsmedia" AS
            SELECT r.uid AS id,
                r.uid_local AS media_id,
                n.uid AS news_id,
                    CASE btrim(r.title::text, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.title::text, ' '::text)
                    END AS title,
                    CASE btrim(r.description, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.description, ' '::text)
                    END AS description,
                    CASE btrim(r.alternative, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.alternative, ' '::text)
                    END AS alternative,
                    CASE
                        WHEN r.sys_language_uid <= 0 THEN NULL::integer
                        ELSE r.sys_language_uid
                    END AS language_id,
                r.sorting AS "order",
                r.showinpreview::integer::boolean AS preview
            FROM
                typo3.news n,
                typo3.file_reference r,
                typo3."content" c
            WHERE
                c.tx_news_related_news = n.uid AND
                c.uid = r.uid_foreign AND
                r.tablenames = 'tt_content' AND
                (r.fieldname = ANY (ARRAY['assets', 'image'])) AND
                r.table_local = 'sys_file' AND
                r.deleted = 0 AND
                r.hidden = 0 AND
                (n.starttime = 0 OR to_timestamp(n.starttime::double precision) < now()) AND
                (n.endtime = 0 OR to_timestamp(n.endtime::double precision) > now()) AND
                n.deleted = 0 AND
                n.hidden = 0 AND
                n.is_event = 0
            UNION ALL
            SELECT r.uid AS id,
                r.uid_local AS media_id,
                r.uid_foreign AS news_id,
                    CASE btrim(r.title::text, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.title::text, ' '::text)
                    END AS title,
                    CASE btrim(r.description, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.description, ' '::text)
                    END AS description,
                    CASE btrim(r.alternative, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.alternative, ' '::text)
                    END AS alternative,
                    CASE
                        WHEN r.sys_language_uid <= 0 THEN NULL::integer
                        ELSE r.sys_language_uid
                    END AS language_id,
                r.sorting AS "order",
                r.showinpreview::integer::boolean AS preview
            FROM
                typo3.news n,
                typo3.file_reference r
            WHERE
            r.tablenames = 'tx_news_domain_model_news' AND
            (r.fieldname = ANY (ARRAY['fal_media', 'fal_related_files'])) AND
            r.uid_foreign = n.uid  AND
            r.table_local = 'sys_file' AND
            r.deleted = 0 AND
            r.hidden = 0 AND
            (n.starttime = 0 OR to_timestamp(n.starttime::double precision) < now()) AND
            (n.endtime = 0 OR to_timestamp(n.endtime::double precision) > now()) AND
            n.deleted = 0 AND
            n.hidden = 0 AND
            n.is_event = 0;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_newsmedia";
            """,
        ),
        (
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_eventmedia";
            """,
            """
            CREATE MATERIALIZED VIEW "public"."typo3_eventmedia" AS
            SELECT
                r.uid AS id,
                r.uid_local AS media_id,
                n.uid AS event_id,
                CASE
                    btrim(r.title, ' ')
                WHEN
                    ''
                THEN
                    NULL
                ELSE
                    btrim(r.title, ' ')
                END AS title,
                CASE
                    btrim(r.description, ' ')
                WHEN
                    ''
                THEN NULL
                ELSE
                    btrim(r.description, ' ')
                END AS description,
                CASE
                    btrim(r.alternative, ' ')
                WHEN
                    ''
                THEN
                    NULL
                ELSE
                    btrim(r.alternative, ' ')
                END AS alternative,
                CASE WHEN
                    r.sys_language_uid <= 0
                THEN
                    NULL
                ELSE
                    r.sys_language_uid
                END AS language_id,
                r.sorting AS "order",
                r.showinpreview::int::boolean AS preview
            FROM
                typo3.news n,
                typo3.file_reference r
            WHERE
                r.tablenames = 'tx_news_domain_model_news'
                AND
                r.table_local = 'sys_file'
                AND
                (
                    r.fieldname = ANY (ARRAY['fal_media', 'fal_related_files'])
                )
                AND
                r.uid_foreign = n.uid
                AND
                r.deleted = 0
                AND
                r.hidden = 0
                AND
                n.datetime <> 0
                AND
                n.event_end <> 0
                AND
                (
                    n.starttime = 0
                    OR
                    to_timestamp(n.starttime) > now()
                )
                AND
                (
                    CASE
                        n.full_day
                    WHEN
                        1
                    THEN
                        to_timestamp(n.event_end) + '24:00:00'::INTERVAL
                    ELSE
                        to_timestamp(n.event_end)
                    END
                ) > now()
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 1
            WITH DATA;
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_eventmedia" AS
            SELECT r.uid AS id,
                r.uid_local AS media_id,
                n.uid AS event_id,
                CASE
                    btrim(r.title::text, ' '::text)
                WHEN
                    ''::text
                THEN
                    NULL::text
                ELSE
                    btrim(r.title::text, ' '::text)
                END AS title,
                CASE
                    btrim(r.description, ' '::text)
                WHEN
                    ''::text THEN NULL::text
                ELSE
                    btrim(r.description, ' '::text)
                END AS description,
                CASE
                    btrim(r.alternative, ' '::text)
                WHEN
                    ''::text THEN NULL::text
                ELSE
                    btrim(r.alternative, ' '::text)
                END AS alternative,
                CASE WHEN
                    r.sys_language_uid <= 0
                THEN
                    NULL::integer
                ELSE
                    r.sys_language_uid
                END AS language_id,
                r.sorting AS "order",
                r.showinpreview::integer::boolean AS preview
            FROM
                typo3.news n,
                typo3.file_reference r,
                typo3.content c
            WHERE
                c.tx_news_related_news = n.uid
                AND
                c.uid = r.uid_foreign
                AND
                r.tablenames = 'tt_content'
                AND
                (
                    r.fieldname::text = ANY (ARRAY['assets'::text, 'image'::text])
                )
                AND
                r.table_local = 'sys_file'
                AND
                    r.deleted = 0
                AND
                r.hidden = 0
                AND
                n.datetime <> 0
                AND
                n.event_end <> 0
                AND
                (
                    n.starttime = 0
                    OR
                    to_timestamp(n.starttime::double precision) > now()
                )
                AND
                CASE
                    n.full_day
                WHEN
                    1
                THEN
                    to_timestamp(n.event_end::double precision) + '24:00:00'::interval
                ELSE
                    to_timestamp(n.event_end::double precision)
                END > now()
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 1
            UNION ALL
            SELECT r.uid AS id,
                r.uid_local AS media_id,
                n.uid AS event_id,
                CASE
                    btrim(r.title::text, ' '::text)
                WHEN
                    ''::text
                THEN
                    NULL::text
                ELSE
                    btrim(r.title::text, ' '::text)
                END AS title,
                CASE
                    btrim(r.description, ' '::text)
                WHEN
                    ''::text THEN NULL::text
                ELSE
                    btrim(r.description, ' '::text)
                END AS description,
                CASE
                    btrim(r.alternative, ' '::text)
                WHEN
                    ''::text THEN NULL::text
                ELSE
                    btrim(r.alternative, ' '::text)
                END AS alternative,
                CASE WHEN
                    r.sys_language_uid <= 0
                THEN
                    NULL::integer
                ELSE
                    r.sys_language_uid
                END AS language_id,
                r.sorting AS "order",
                r.showinpreview::integer::boolean AS preview
            FROM
                typo3.news n,
                typo3.file_reference r
            WHERE
                r.tablenames::text = 'tx_news_domain_model_news'::text
                AND
                r.table_local::text = 'sys_file'::text
                AND
                (
                    r.fieldname::text = ANY (ARRAY['fal_media'::text, 'fal_related_files'::text])
                )
                AND
                r.uid_foreign = n.uid
                AND
                r.deleted = 0
                AND
                r.hidden = 0
                AND
                n.datetime <> 0
                AND
                n.event_end <> 0
                AND
                (
                    n.starttime = 0
                    OR
                    to_timestamp(n.starttime::double precision) > now())
                AND
                CASE
                    n.full_day
                WHEN
                    1
                THEN
                    to_timestamp(n.event_end::double precision) + '24:00:00'::interval
                ELSE
                    to_timestamp(n.event_end::double precision)
                END > now()
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 1
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_eventmedia";
            """,
        ),
    ]

    dependencies = [("typo3", "0003_views")]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
