# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-23 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    ops = [
        (
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_news";
            """,
            """
            CREATE MATERIALIZED VIEW "public"."typo3_news" AS
            SELECT
                n.uid AS id,
                n.pid AS source_id,
                CASE WHEN
                    n.sys_language_uid > 0
                THEN
                    n.sys_language_uid
                ELSE
                    NULL::integer
                END AS language_id,
                CASE
                    n.datetime
                WHEN
                    0
                THEN
                    NULL::timestamp WITH time ZONE
                ELSE
                    to_timestamp(n.datetime)
                END AS datetime,
                html_unescape(n.title) AS title,
                html_unescape(n.teaser) AS teaser,
                html_unescape(n.bodytext) AS body,
                CASE
                    n.starttime
                WHEN
                    0
                THEN
                    NULL::timestamp WITH time ZONE
                ELSE
                    to_timestamp(n.starttime)
                END AS START,
                CASE
                    n.endtime
                WHEN
                    0
                THEN
                    NULL::timestamp WITH time ZONE
                ELSE
                    to_timestamp(n.endtime)
                END AS "end",
                NULLIF(BTRIM(n.author, ' '), '') AS author,
                NULLIF(BTRIM(n.author_email, ' '), '') AS email,
                NULLIF(BTRIM(n.keywords, ' '), '') AS keywords,
                n.tags AS tags,
                n.istopnews = 1 AS topnews,
                to_timestamp(n.tstamp) AS last_modified
            FROM
                typo3.news AS n
            WHERE
                (
                    n.starttime = 0
                    OR
                    n.starttime < date_part('epoch'::text, now())
                )
                AND
                (
                    n.endtime = 0
                    OR
                    n.endtime > date_part('epoch'::text, now())
                )
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 0
                WITH DATA;
            """,
        ),
        (
            """
            ALTER FOREIGN TABLE "typo3"."news" ADD COLUMN t3ver_wsid int;
            """,
            """
            ALTER FOREIGN TABLE "typo3"."news" DROP COLUMN t3ver_wsid;
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_news" AS
            SELECT
                n.uid AS id,
                n.pid AS source_id,
                CASE WHEN
                    n.sys_language_uid > 0
                THEN
                    n.sys_language_uid
                ELSE
                    NULL::integer
                END AS language_id,
                CASE
                    n.datetime
                WHEN
                    0
                THEN
                    NULL::timestamp WITH time ZONE
                ELSE
                    to_timestamp(n.datetime)
                END AS datetime,
                html_unescape(n.title) AS title,
                html_unescape(n.teaser) AS teaser,
                html_unescape(n.bodytext) AS body,
                CASE
                    n.starttime
                WHEN
                    0
                THEN
                    NULL::timestamp WITH time ZONE
                ELSE
                    to_timestamp(n.starttime)
                END AS START,
                CASE
                    n.endtime
                WHEN
                    0
                THEN
                    NULL::timestamp WITH time ZONE
                ELSE
                    to_timestamp(n.endtime)
                END AS "end",
                NULLIF(BTRIM(n.author, ' '), '') AS author,
                NULLIF(BTRIM(n.author_email, ' '), '') AS email,
                NULLIF(BTRIM(n.keywords, ' '), '') AS keywords,
                n.tags AS tags,
                n.istopnews = 1 AS topnews,
                to_timestamp(n.tstamp) AS last_modified
            FROM
                typo3.news AS n
            WHERE
                (
                    n.starttime = 0
                    OR
                    n.starttime < date_part('epoch'::text, now())
                )
                AND
                (
                    n.endtime = 0
                    OR
                    n.endtime > date_part('epoch'::text, now())
                )
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 0
                AND
                n.t3ver_wsid = 0
                WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_news";
            """,
        ),
    ]

    dependencies = [
        ("typo3", "0004_content"),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
