# Generated by Django 2.2.28 on 2023-04-05 19:19

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    ops = [
        (
            """
            CREATE FOREIGN TABLE "typo3"."news_links" (
                uid int,
                pid int,
                tstamp bigint,
                crdate bigint,
                cruser_id int,
                sys_language_uid smallint,
                sorting int,
                deleted smallint,
                hidden smallint,
                parent int,
                title varchar,
                description text,
                uri text
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'tx_news_domain_model_link',
                primary_key 'uid',
                db_url '{typo3}'
            );
            """.format(
                typo3=settings.MULTICORN.get("typo3")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "typo3"."news_links";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_news_related_link" AS
            SELECT
                nl.uid AS id,
                nl.pid AS source_id,
                CASE
                    WHEN nl.sys_language_uid > 0 THEN nl.sys_language_uid
                    ELSE NULL::integer
                END AS language_id,
                CASE nl.tstamp
                    WHEN 0 THEN NULL::timestamp with time zone
                    ELSE to_timestamp(nl.tstamp ::double precision)
                END AS datetime,
                nl.parent AS news_id,
                nl.sorting AS order,
                TRIM(html_unescape(nl.title)) AS title,
                NULLIF(TRIM(html_unescape(nl.description)), '') AS description,
                nl.uri AS url
            FROM typo3.news_links nl
            INNER JOIN typo3.news n ON n.uid = nl.parent
            WHERE
                (n.starttime = 0 OR to_timestamp(n.starttime::double precision) < now()) AND
                (n.endtime = 0 OR to_timestamp(n.endtime::double precision) > now()) AND
                n.deleted = 0 AND
                n.hidden = 0 AND
                n.is_event = 0 AND
                n.t3ver_wsid = 0 AND
                nl.deleted = 0 AND
                nl.hidden = 0 AND
                nl.uri ^@ 'https://'
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_news_related_link";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_news_related_media" AS
            SELECT
                nl.uid AS id,
                nl.pid AS source_id,
                CASE
                    WHEN nl.sys_language_uid > 0 THEN nl.sys_language_uid
                    ELSE NULL::integer
                END AS language_id,
                CASE nl.tstamp
                    WHEN 0 THEN NULL::timestamp with time zone
                    ELSE to_timestamp(nl.tstamp ::double precision)
                END AS datetime,
                nl.parent AS news_id,
                nl.sorting AS order,
                TRIM(html_unescape(nl.title)) AS title,
                NULLIF(TRIM(html_unescape(nl.description)), '') AS description,
                f.uid AS media_id
            FROM typo3.news_links nl
            INNER JOIN typo3.news n ON n.uid = nl.parent
            INNER JOIN typo3.file f ON f.uid = CASE WHEN nl.uri ^@ 'file:' THEN substring(nl.uri FROM '^file:(\d+)') WHEN nl.uri ^@ 't3://file?uid=' THEN substring(nl.uri FROM '^t3://file\?uid=(\d+)') END::integer
            WHERE
                (n.starttime = 0 OR to_timestamp(n.starttime::double precision) < now()) AND
                (n.endtime = 0 OR to_timestamp(n.endtime::double precision) > now()) AND
                n.deleted = 0 AND
                n.hidden = 0 AND
                n.is_event = 0 AND
                n.t3ver_wsid = 0 AND
                f.storage > 0 AND
                f.missing = 0 AND
                nl.deleted = 0 AND
                nl.hidden = 0 AND
                (
                    nl.uri ^@ 'file:' OR
                    nl.uri ^@ 't3://file?uid='
                )
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_news_related_media";
            """,
        ),
    ]

    dependencies = [
        ("typo3", "0005_news_filter"),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
