# Generated by Django 2.2.28 on 2023-12-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    ops = [
        (
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_newsmedia";
            """,
            """
            CREATE MATERIALIZED VIEW "public"."typo3_newsmedia" AS
            SELECT r.uid AS id,
                r.uid_local AS media_id,
                n.uid AS news_id,
                    CASE btrim(r.title::text, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.title::text, ' '::text)
                    END AS title,
                    CASE btrim(r.description, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.description, ' '::text)
                    END AS description,
                    CASE btrim(r.alternative, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.alternative, ' '::text)
                    END AS alternative,
                    CASE
                        WHEN r.sys_language_uid <= 0 THEN NULL::integer
                        ELSE r.sys_language_uid
                    END AS language_id,
                r.sorting AS "order",
                r.showinpreview::integer::boolean AS preview
            FROM
                typo3.news n,
                typo3.file_reference r,
                typo3."content" c
            WHERE
                c.tx_news_related_news = n.uid AND
                c.uid = r.uid_foreign AND
                r.tablenames = 'tt_content' AND
                (r.fieldname = ANY (ARRAY['assets', 'image'])) AND
                r.table_local = 'sys_file' AND
                r.deleted = 0 AND
                r.hidden = 0 AND
                (n.starttime = 0 OR to_timestamp(n.starttime::double precision) < now()) AND
                (n.endtime = 0 OR to_timestamp(n.endtime::double precision) > now()) AND
                n.deleted = 0 AND
                n.hidden = 0 AND
                n.is_event = 0
            UNION ALL
            SELECT r.uid AS id,
                r.uid_local AS media_id,
                n.uid AS news_id,
                    CASE btrim(r.title::text, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.title::text, ' '::text)
                    END AS title,
                    CASE btrim(r.description, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.description, ' '::text)
                    END AS description,
                    CASE btrim(r.alternative, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.alternative, ' '::text)
                    END AS alternative,
                    CASE
                        WHEN r.sys_language_uid <= 0 THEN NULL::integer
                        ELSE r.sys_language_uid
                    END AS language_id,
                r.sorting AS "order",
                r.showinpreview::integer::boolean AS preview
            FROM
                typo3.news n,
                typo3.file_reference r
            WHERE
                r.tablenames = 'tx_news_domain_model_news' AND
                (r.fieldname = ANY (ARRAY['fal_media', 'fal_related_files'])) AND
                r.uid_foreign = n.uid  AND
                r.table_local = 'sys_file' AND
                r.deleted = 0 AND
                r.hidden = 0 AND
                (n.starttime = 0 OR to_timestamp(n.starttime::double precision) < now()) AND
                (n.endtime = 0 OR to_timestamp(n.endtime::double precision) > now()) AND
                n.deleted = 0 AND
                n.hidden = 0 AND
                n.is_event = 0
            WITH DATA;
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_newsmedia" AS
            SELECT r.uid AS id,
                r.uid_local AS media_id,
                n.uid AS news_id,
                    CASE btrim(r.title::text, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.title::text, ' '::text)
                    END AS title,
                    CASE btrim(r.description, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.description, ' '::text)
                    END AS description,
                    CASE btrim(r.alternative, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.alternative, ' '::text)
                    END AS alternative,
                    CASE
                        WHEN r.sys_language_uid <= 0 THEN NULL::integer
                        ELSE r.sys_language_uid
                    END AS language_id,
                r.sorting AS "order",
                false AS preview
            FROM
                typo3.news n,
                typo3.file_reference r,
                typo3."content" c
            WHERE
                c.tx_news_related_news = n.uid AND
                c.uid = r.uid_foreign AND
                r.tablenames = 'tt_content' AND
                (r.fieldname = ANY (ARRAY['assets', 'image'])) AND
                r.table_local = 'sys_file' AND
                r.deleted = 0 AND
                r.hidden = 0 AND
                (n.starttime = 0 OR n.starttime < extract(epoch from now())) AND
                (n.endtime = 0 OR n.endtime > extract(epoch from now())) AND
                n.deleted = 0 AND
                n.hidden = 0 AND
                n.is_event = 0
            UNION ALL
            SELECT r.uid AS id,
                r.uid_local AS media_id,
                n.uid AS news_id,
                    CASE btrim(r.title::text, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.title::text, ' '::text)
                    END AS title,
                    CASE btrim(r.description, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.description, ' '::text)
                    END AS description,
                    CASE btrim(r.alternative, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.alternative, ' '::text)
                    END AS alternative,
                    CASE
                        WHEN r.sys_language_uid <= 0 THEN NULL::integer
                        ELSE r.sys_language_uid
                    END AS language_id,
                r.sorting AS "order",
                r.showinpreview::integer::boolean AND r.fieldname = 'fal_media' AS preview
            FROM
                typo3.news n,
                typo3.file_reference r
            WHERE
                r.tablenames = 'tx_news_domain_model_news' AND
                (r.fieldname = ANY (ARRAY['fal_media', 'fal_related_files'])) AND
                r.uid_foreign = n.uid  AND
                r.table_local = 'sys_file' AND
                r.deleted = 0 AND
                r.hidden = 0 AND
                (n.starttime = 0 OR n.starttime < extract(epoch from now())) AND
                (n.endtime = 0 OR n.endtime > extract(epoch from now())) AND
                n.deleted = 0 AND
                n.hidden = 0 AND
                n.is_event = 0
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_newsmedia";
            """,
        ),
    ]

    dependencies = [
        ("typo3", "0008_auto_20230919_1113"),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
