# Generated by Django 2.2.28 on 2024-04-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    ops = [
        (
            """
            ALTER FOREIGN TABLE typo3.content
                ADD COLUMN subheader text NULL,
                ADD COLUMN mugce_link_label text NULL,
                ADD COLUMN mugce_subheader text NULL,
                ADD COLUMN mugce_caption text NULL,
                ADD COLUMN mugce_text_3 text NULL,
                ADD COLUMN mugce_text_4 text NULL;
            """,
            """
            ALTER FOREIGN TABLE typo3.content
                DROP COLUMN subheader,
                DROP COLUMN mugce_link_label,
                DROP COLUMN mugce_subheader,
                DROP COLUMN mugce_caption,
                DROP COLUMN mugce_text_3,
                DROP COLUMN mugce_text_4;
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_newsgallery" AS
            SELECT
                r.uid AS id,
                r.uid_local AS media_id,
                n.uid AS news_id,
                CASE
                    btrim(r.title,
                    ' ')
                        WHEN '' THEN NULL
                    ELSE btrim(r.title,
                    ' ')
                END AS title,
                CASE
                    btrim(r.description,
                    ' ')
                        WHEN '' THEN NULL
                    ELSE btrim(r.description,
                    ' '::TEXT)
                END AS description,
                CASE
                    btrim(r.alternative,
                    ' '::TEXT)
                    WHEN ''::TEXT THEN NULL::TEXT
                    ELSE btrim(r.alternative,
                    ' '::TEXT)
                END AS alternative,
                CASE
                    WHEN r.sys_language_uid <= 0 THEN NULL::integer
                    ELSE r.sys_language_uid
                END AS language_id,
                r.sorting AS "order"
            FROM
                typo3.news n,
                typo3.file_reference r,
                typo3.content c
            WHERE
                c.CType = 'mugce_gallery'
                AND c.tx_news_related_news = n.uid
                AND c.uid = r.uid_foreign
                AND r.tablenames::TEXT = 'tt_content'::TEXT
                AND (r.fieldname::TEXT = ANY (ARRAY['assets'::TEXT,
                'image'::TEXT]))
                AND r.table_local::TEXT = 'sys_file'::TEXT
                AND r.deleted = 0
                AND r.hidden = 0
                AND (n.starttime = 0
                    OR n.starttime::double PRECISION < date_part('epoch'::TEXT,
                    now()))
                AND (n.endtime = 0
                    OR n.endtime::double PRECISION > date_part('epoch'::TEXT,
                    now()))
                AND n.deleted = 0
                AND n.hidden = 0
                AND n.t3ver_wsid = 0
                AND n.is_event = 0
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_newsgallery";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_newscontactbox" AS
            SELECT
                c.uid AS id,
                n.uid AS news_id,
                r.uid_local as media_id,
                c.header AS title,
                c.bodytext AS name,
                CASE
                    btrim(c.subheader,
                    ' '::TEXT)
                    WHEN ''::TEXT THEN NULL::TEXT
                    ELSE btrim(c.subheader,
                    ' '::TEXT)
                END AS phone,
                CASE
                    btrim(c.header_link,
                    ' '::TEXT)
                    WHEN ''::TEXT THEN NULL::TEXT
                    ELSE btrim(c.header_link,
                    ' '::TEXT)
                END AS url,
                CASE
                    btrim(c.mugce_link_label,
                    ' '::TEXT)
                    WHEN ''::TEXT THEN NULL::TEXT
                    ELSE btrim(c.mugce_link_label,
                    ' '::TEXT)
                END AS link_label,
                CASE
                    btrim(c.mugce_subheader,
                    ' '::TEXT)
                    WHEN ''::TEXT THEN NULL::TEXT
                    ELSE btrim(c.mugce_subheader,
                    ' '::TEXT)
                END AS email,
                CASE
                    btrim(c.mugce_caption,
                    ' '::TEXT)
                    WHEN ''::TEXT THEN NULL::TEXT
                    ELSE btrim(c.mugce_caption,
                    ' '::TEXT)
                END AS headline,
                ARRAY[c.mugce_text_3,
                mugce_text_4] AS address
            FROM
                typo3.content c,
                typo3.file_reference r,
                typo3.news n
            WHERE
                c.uid = r.uid_foreign
                AND c.tx_news_related_news = n.uid
                AND r.tablenames = 'tt_content'
                AND c.ctype = 'mugce_contact'
                AND (r.fieldname::TEXT = ANY (ARRAY['assets'::TEXT,
                'image'::TEXT]))
                AND r.table_local::TEXT = 'sys_file'::TEXT
                AND r.deleted = 0
                AND r.hidden = 0
                AND n.t3ver_wsid = 0
                and n.is_event = 0
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_newscontactbox";
            """,
        ),
        (
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_newsmedia";
            """,
            """
            CREATE MATERIALIZED VIEW "public"."typo3_newsmedia" AS
            SELECT r.uid AS id,
                r.uid_local AS media_id,
                n.uid AS news_id,
                    CASE btrim(r.title::text, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.title::text, ' '::text)
                    END AS title,
                    CASE btrim(r.description, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.description, ' '::text)
                    END AS description,
                    CASE btrim(r.alternative, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.alternative, ' '::text)
                    END AS alternative,
                    CASE
                        WHEN r.sys_language_uid <= 0 THEN NULL::integer
                        ELSE r.sys_language_uid
                    END AS language_id,
                r.sorting AS "order",
                false AS preview
            FROM
                typo3.news n,
                typo3.file_reference r,
                typo3."content" c
            WHERE
                c.tx_news_related_news = n.uid AND
                c.uid = r.uid_foreign AND
                r.tablenames = 'tt_content' AND
                (r.fieldname = ANY (ARRAY['assets', 'image'])) AND
                r.table_local = 'sys_file' AND
                r.deleted = 0 AND
                r.hidden = 0 AND
                (n.starttime = 0 OR n.starttime < extract(epoch from now())) AND
                (n.endtime = 0 OR n.endtime > extract(epoch from now())) AND
                n.deleted = 0 AND
                n.hidden = 0 AND
                n.is_event = 0
            UNION ALL
            SELECT r.uid AS id,
                r.uid_local AS media_id,
                n.uid AS news_id,
                    CASE btrim(r.title::text, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.title::text, ' '::text)
                    END AS title,
                    CASE btrim(r.description, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.description, ' '::text)
                    END AS description,
                    CASE btrim(r.alternative, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.alternative, ' '::text)
                    END AS alternative,
                    CASE
                        WHEN r.sys_language_uid <= 0 THEN NULL::integer
                        ELSE r.sys_language_uid
                    END AS language_id,
                r.sorting AS "order",
                r.showinpreview::integer::boolean AND r.fieldname = 'fal_media' AS preview
            FROM
                typo3.news n,
                typo3.file_reference r
            WHERE
                r.tablenames = 'tx_news_domain_model_news' AND
                (r.fieldname = ANY (ARRAY['fal_media', 'fal_related_files'])) AND
                r.uid_foreign = n.uid  AND
                r.table_local = 'sys_file' AND
                r.deleted = 0 AND
                r.hidden = 0 AND
                (n.starttime = 0 OR n.starttime < extract(epoch from now())) AND
                (n.endtime = 0 OR n.endtime > extract(epoch from now())) AND
                n.deleted = 0 AND
                n.hidden = 0 AND
                n.is_event = 0
            WITH DATA;
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_newsmedia" AS
            SELECT
                r.uid AS id,
                r.uid_local AS media_id,
                n.uid AS news_id,
                CASE
                    btrim(r.title,
                    ' ')
                        WHEN '' THEN NULL
                    ELSE btrim(r.title,
                    ' ')
                END AS title,
                CASE
                    btrim(r.description,
                    ' ')
                        WHEN '' THEN NULL
                    ELSE btrim(r.description,
                    ' '::TEXT)
                END AS description,
                CASE
                    btrim(r.alternative,
                    ' '::TEXT)
                    WHEN ''::TEXT THEN NULL::TEXT
                    ELSE btrim(r.alternative,
                    ' '::TEXT)
                END AS alternative,
                CASE
                    WHEN r.sys_language_uid <= 0 THEN NULL::integer
                    ELSE r.sys_language_uid
                END AS language_id,
                r.sorting AS "order"
            FROM
                typo3.news n,
                typo3.file_reference r,
                typo3.content c
            WHERE
                c.ctype != 'mugce_contact'
                AND c.ctype != 'mugce_gallery'
                AND c.tx_news_related_news = n.uid
                AND c.uid = r.uid_foreign
                AND r.tablenames::TEXT = 'tt_content'::TEXT
                AND (r.fieldname::TEXT = ANY (ARRAY['assets'::TEXT, 'image'::TEXT]))
                AND r.table_local::TEXT = 'sys_file'::TEXT
                AND r.deleted = 0
                AND r.hidden = 0
                AND (n.starttime = 0
                    OR n.starttime::double PRECISION < date_part('epoch'::TEXT,
                    now()))
                AND (n.endtime = 0
                    OR n.endtime::double PRECISION > date_part('epoch'::TEXT,
                    now()))
                AND n.deleted = 0
                AND n.hidden = 0
                AND n.t3ver_wsid = 0
                AND n.is_event = 0
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_newsmedia";
            """,
        ),
        (
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_news";
            """,
            """
            CREATE MATERIALIZED VIEW "public"."typo3_news" AS
            SELECT
                n.uid AS id,
                n.pid AS source_id,
                CASE WHEN
                    n.sys_language_uid > 0
                THEN
                    n.sys_language_uid
                ELSE
                    NULL::integer
                END AS language_id,
                CASE
                    n.datetime
                WHEN
                    0
                THEN
                    NULL::timestamp WITH time ZONE
                ELSE
                    to_timestamp(n.datetime)
                END AS datetime,
                html_unescape(n.title) AS title,
                html_unescape(n.teaser) AS teaser,
                html_unescape(n.bodytext) AS body,
                CASE
                    n.starttime
                WHEN
                    0
                THEN
                    NULL::timestamp WITH time ZONE
                ELSE
                    to_timestamp(n.starttime)
                END AS START,
                CASE
                    n.endtime
                WHEN
                    0
                THEN
                    NULL::timestamp WITH time ZONE
                ELSE
                    to_timestamp(n.endtime)
                END AS "end",
                NULLIF(BTRIM(n.author, ' '), '') AS author,
                NULLIF(BTRIM(n.author_email, ' '), '') AS email,
                regexp_split_to_array(NULLIF(TRIM(n.keywords), ''), '\s*,\s*') AS keywords,
                NULLIF(TRIM(n.description), '') AS description,
                n.tags AS tags,
                n.istopnews = 1 AS topnews,
                to_timestamp(n.tstamp) AS last_modified
            FROM
                typo3.news AS n
            WHERE
                (
                    n.starttime = 0
                    OR
                    n.starttime < extract(epoch from now())
                )
                AND
                (
                    n.endtime = 0
                    OR
                    n.endtime > extract(epoch from now())
                )
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 0
                AND
                n.t3ver_wsid = 0
                WITH DATA;
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_news" AS
            SELECT n.uid AS id,
                n.pid AS source_id,
                    CASE
                        WHEN n.sys_language_uid > 0 THEN n.sys_language_uid
                        ELSE NULL::integer
                    END AS language_id,
                    CASE n.datetime
                        WHEN 0 THEN NULL::timestamp with time zone
                        ELSE to_timestamp(n.datetime::double precision)
                    END AS datetime,
                html_unescape(n.title) AS title,
                html_unescape(n.teaser) AS teaser,
                html_unescape(n.bodytext) AS body,
                    CASE n.starttime
                        WHEN 0 THEN NULL::timestamp with time zone
                        ELSE to_timestamp(n.starttime::double precision)
                    END AS start,
                    CASE n.endtime
                        WHEN 0 THEN NULL::timestamp with time zone
                        ELSE to_timestamp(n.endtime::double precision)
                    END AS "end",
                NULLIF(btrim(n.author, ' '::text), ''::text) AS author,
                NULLIF(btrim(n.author_email, ' '::text), ''::text) AS email,
                regexp_split_to_array(NULLIF(btrim(n.keywords), ''::text), '\s*,\s*'::text) AS keywords,
                NULLIF(btrim(n.description), ''::text) AS description,
                n.tags,
                n.istopnews = 1 AS topnews,
                to_timestamp(n.tstamp::double precision) AS last_modified,
                (
                    SELECT
                        fr.uid_local
                    FROM typo3.file_reference fr
                    WHERE
                        fr.uid_foreign = n.uid AND
                        fr.tablenames = 'tx_news_domain_model_news' AND
                        fieldname = 'fal_media' AND
                        fr.showinpreview = 1 AND
                        fr.hidden = 0 AND
                        fr.deleted = 0
                    ORDER BY fr.sorting
                    LIMIT 1
                ) AS header_image_id
            FROM typo3.news n
            WHERE
                (n.starttime = 0 OR n.starttime < extract(epoch from now())) and
                (n.endtime = 0 OR n.endtime > extract(epoch from now())) and
                n.deleted = 0 and
                n.hidden = 0 and
                n.is_event = 0 and
                n.t3ver_wsid = 0
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_news";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_eventgallery" AS
            SELECT
                r.uid AS id,
                r.uid_local AS media_id,
                n.uid AS event_id,
                CASE
                    btrim(r.title,
                    ' ')
                        WHEN '' THEN NULL
                    ELSE btrim(r.title,
                    ' ')
                END AS title,
                CASE
                    btrim(r.description,
                    ' ')
                        WHEN '' THEN NULL
                    ELSE btrim(r.description,
                    ' '::TEXT)
                END AS description,
                CASE
                    btrim(r.alternative,
                    ' '::TEXT)
                    WHEN ''::TEXT THEN NULL::TEXT
                    ELSE btrim(r.alternative,
                    ' '::TEXT)
                END AS alternative,
                CASE
                    WHEN r.sys_language_uid <= 0 THEN NULL::integer
                    ELSE r.sys_language_uid
                END AS language_id,
                r.sorting AS "order"
            FROM
                typo3.news n,
                typo3.file_reference r,
                typo3.content c
            WHERE
                c.CType = 'mugce_gallery'
                AND c.tx_news_related_news = n.uid
                AND c.uid = r.uid_foreign
                AND r.tablenames::TEXT = 'tt_content'::TEXT
                AND (r.fieldname::TEXT = ANY (ARRAY['assets'::TEXT, 'image'::TEXT]))
                AND r.table_local::TEXT = 'sys_file'::TEXT
                AND r.deleted = 0
                AND r.hidden = 0
                AND n.datetime <> 0
                AND n.event_end <> 0
                AND (n.starttime = 0 OR n.starttime > date_part('epoch'::TEXT, now()))
                AND CASE n.full_day
                    WHEN 1 THEN
                        n.event_end + 86400
                    ELSE
                        n.event_end
                    END > date_part('epoch'::TEXT, now())
                AND n.deleted = 0
                AND n.hidden = 0
                AND n.t3ver_wsid = 0
                AND n.is_event = 1
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_eventgallery";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_eventcontactbox" AS
            SELECT
                c.uid AS id,
                n.uid AS event_id,
                r.uid_local as media_id,
                c.header AS title,
                c.bodytext AS name,
                CASE
                    btrim(c.subheader,
                    ' '::TEXT)
                    WHEN ''::TEXT THEN NULL::TEXT
                    ELSE btrim(c.subheader,
                    ' '::TEXT)
                END AS phone,
                CASE
                    btrim(c.header_link,
                    ' '::TEXT)
                    WHEN ''::TEXT THEN NULL::TEXT
                    ELSE btrim(c.header_link,
                    ' '::TEXT)
                END AS url,
                CASE
                    btrim(c.mugce_link_label,
                    ' '::TEXT)
                    WHEN ''::TEXT THEN NULL::TEXT
                    ELSE btrim(c.mugce_link_label,
                    ' '::TEXT)
                END AS link_label,
                CASE
                    btrim(c.mugce_subheader,
                    ' '::TEXT)
                    WHEN ''::TEXT THEN NULL::TEXT
                    ELSE btrim(c.mugce_subheader,
                    ' '::TEXT)
                END AS email,
                CASE
                    btrim(c.mugce_caption,
                    ' '::TEXT)
                    WHEN ''::TEXT THEN NULL::TEXT
                    ELSE btrim(c.mugce_caption,
                    ' '::TEXT)
                END AS headline,
                ARRAY[c.mugce_text_3,
                mugce_text_4] AS address
            FROM
                typo3.content c,
                typo3.file_reference r,
                typo3.news n
            WHERE
                c.uid = r.uid_foreign
                AND c.tx_news_related_news = n.uid
                AND r.tablenames = 'tt_content'
                AND c.ctype = 'mugce_contact'
                AND (r.fieldname::TEXT = ANY (ARRAY['assets'::TEXT, 'image'::TEXT]))
                AND r.table_local::TEXT = 'sys_file'::TEXT
                AND r.deleted = 0
                AND r.hidden = 0
                AND n.datetime <> 0
                AND n.event_end <> 0
                AND (n.starttime = 0 OR n.starttime > date_part('epoch'::TEXT, now()))
                AND CASE n.full_day
                    WHEN 1 THEN
                        n.event_end + 86400
                    ELSE
                        n.event_end
                    END > date_part('epoch'::TEXT, now())
                AND n.deleted = 0
                AND n.hidden = 0
                AND n.t3ver_wsid = 0
                AND n.is_event = 1
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_eventcontactbox";
            """,
        ),
        (
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_eventmedia";
            """,
            """
            CREATE MATERIALIZED VIEW public.typo3_eventmedia AS
            SELECT r.uid AS id,
                r.uid_local AS media_id,
                n.uid AS event_id,
                    CASE btrim(r.title::text, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.title::text, ' '::text)
                    END AS title,
                    CASE btrim(r.description, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.description, ' '::text)
                    END AS description,
                    CASE btrim(r.alternative, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.alternative, ' '::text)
                    END AS alternative,
                    CASE
                        WHEN r.sys_language_uid <= 0 THEN NULL::integer
                        ELSE r.sys_language_uid
                    END AS language_id,
                r.sorting AS "order",
                r.showinpreview::integer::boolean AS preview
            FROM typo3.news n,
                typo3.file_reference r,
                typo3.content c
            WHERE
                c.tx_news_related_news = n.uid AND
                c.uid = r.uid_foreign AND
                r.tablenames::text = 'tt_content'::text AND
                (
                    r.fieldname::text = ANY (ARRAY['assets'::text, 'image'::text])
                ) AND
                r.table_local::text = 'sys_file'::text AND
                r.deleted = 0 AND
                r.hidden = 0 AND
                n.datetime <> 0 AND
                n.event_end <> 0 AND
                (
                    n.starttime = 0 OR
                    n.starttime > extract(epoch from now())
                ) AND
                CASE n.full_day
                    WHEN 1 THEN n.event_end + 86400
                    ELSE n.event_end
                END > extract(epoch from now()) AND
                n.deleted = 0 AND
                n.hidden = 0 AND
                n.is_event = 1
            UNION ALL
            SELECT r.uid AS id,
                r.uid_local AS media_id,
                n.uid AS event_id,
                    CASE btrim(r.title::text, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.title::text, ' '::text)
                    END AS title,
                    CASE btrim(r.description, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.description, ' '::text)
                    END AS description,
                    CASE btrim(r.alternative, ' '::text)
                        WHEN ''::text THEN NULL::text
                        ELSE btrim(r.alternative, ' '::text)
                    END AS alternative,
                    CASE
                        WHEN r.sys_language_uid <= 0 THEN NULL::integer
                        ELSE r.sys_language_uid
                    END AS language_id,
                r.sorting AS "order",
                r.showinpreview::integer::boolean AS preview
            FROM typo3.news n,
                typo3.file_reference r
            WHERE
                r.tablenames::text = 'tx_news_domain_model_news'::text AND
                r.table_local::text = 'sys_file'::text AND
                (
                    r.fieldname::text = ANY (ARRAY['fal_media'::text, 'fal_related_files'::text])
                ) AND
                r.uid_foreign = n.uid AND
                r.deleted = 0 AND
                r.hidden = 0 AND
                n.datetime <> 0 AND
                n.event_end <> 0
                AND (
                    n.starttime = 0 OR
                    n.starttime > extract(epoch from now())
                ) AND
                CASE n.full_day
                    WHEN 1 THEN n.event_end + 86400
                    ELSE n.event_end
                END > extract(epoch from now()) AND
                n.deleted = 0 AND
                n.hidden = 0 AND
                n.is_event = 1
            WITH DATA;
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_eventmedia" AS
            SELECT
                r.uid AS id,
                r.uid_local AS media_id,
                n.uid AS event_id,
                CASE
                    btrim(r.title,
                    ' ')
                        WHEN '' THEN NULL
                    ELSE btrim(r.title,
                    ' ')
                END AS title,
                CASE
                    btrim(r.description,
                    ' ')
                        WHEN '' THEN NULL
                    ELSE btrim(r.description,
                    ' '::TEXT)
                END AS description,
                CASE
                    btrim(r.alternative,
                    ' '::TEXT)
                    WHEN ''::TEXT THEN NULL::TEXT
                    ELSE btrim(r.alternative,
                    ' '::TEXT)
                END AS alternative,
                CASE
                    WHEN r.sys_language_uid <= 0 THEN NULL::integer
                    ELSE r.sys_language_uid
                END AS language_id,
                r.sorting AS "order"
            FROM
                typo3.news n,
                typo3.file_reference r,
                typo3.content c
            WHERE
                c.ctype != 'mugce_contact'
                AND c.ctype != 'mugce_gallery'
                AND c.tx_news_related_news = n.uid
                AND c.uid = r.uid_foreign
                AND r.tablenames::TEXT = 'tt_content'::TEXT
                AND (r.fieldname::TEXT = ANY (ARRAY['assets'::TEXT, 'image'::TEXT]))
                AND r.table_local::TEXT = 'sys_file'::TEXT
                AND r.deleted = 0
                AND r.hidden = 0
                AND n.datetime <> 0
                AND n.event_end <> 0
                AND (n.starttime = 0 OR n.starttime > date_part('epoch'::TEXT, now()))
                AND CASE n.full_day
                    WHEN 1 THEN
                        n.event_end + 86400
                    ELSE
                        n.event_end
                    END > date_part('epoch'::TEXT, now())
                AND n.deleted = 0
                AND n.hidden = 0
                AND n.t3ver_wsid = 0
                AND n.is_event = 1
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_eventmedia";
            """,
        ),
        (
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_event";
            """,
            """
            CREATE MATERIALIZED VIEW public.typo3_event AS
            SELECT n.uid AS id,
                n.pid AS source_id,
                to_timestamp(n.datetime::double precision) AS start,
                    CASE n.event_end
                        WHEN 0 THEN (to_timestamp(n.datetime::double precision)::date + '24:00:00'::interval)::timestamp with time zone
                        ELSE to_timestamp(n.event_end::double precision)
                    END AS "end",
                n.full_day::integer::boolean AS allday,
                html_unescape(n.title) AS title,
                NULLIF(btrim(n.organizer_simple::text, ' '::text), ''::text) AS organizer,
                NULLIF(btrim(n.location_simple::text, ' '::text), ''::text) AS location,
                html_unescape(n.teaser) AS teaser,
                html_unescape(n.bodytext) AS body,
                regexp_split_to_array(NULLIF(btrim(n.keywords), ''::text), '\s*,\s*'::text) AS keywords,
                NULLIF(btrim(n.description), ''::text) AS description,
                    CASE
                        WHEN n.sys_language_uid > 0 THEN n.sys_language_uid
                        ELSE NULL::integer
                    END AS language_id,
                n.register::integer::boolean AS register,
                    CASE
                        WHEN n.registration_end > 0 THEN to_timestamp(n.registration_end::double precision)
                        ELSE NULL::timestamp with time zone
                    END AS registration_end,
                n.attendingfees::integer::boolean AS attending_fees,
                NULLIF(btrim(n.attendingfees_info), ''::text) AS attending_fees_info,
                NULLIF(btrim(n.www::text, ' '::text), ''::text) AS link,
                    CASE
                        WHEN n.dfppoints > 0 THEN n.dfppoints
                        ELSE NULL::integer
                    END AS dfp_points,
                NULLIF(btrim(n.contact_name::text, ' '::text), ''::text) AS contact,
                NULLIF(btrim(n.contact_email::text, ' '::text), ''::text) AS email,
                to_timestamp(n.tstamp::double precision) AS last_modified
            FROM typo3.news n
            WHERE n.datetime <> 0 AND (n.starttime = 0 OR n.starttime::double precision > date_part('epoch'::text, now())) AND
                    CASE n.event_end
                        WHEN 0 THEN n.datetime + 86400
                        ELSE n.event_end
                    END > extract(epoch from now()) AND
                    n.deleted = 0 AND
                    n.hidden = 0 AND
                    n.is_event = 1 AND
                    n.t3ver_wsid = 0
            WITH DATA;
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW public.typo3_event AS
            SELECT n.uid AS id,
                n.pid AS source_id,
                to_timestamp(n.datetime::double precision) AS start,
                    CASE n.event_end
                        WHEN 0 THEN (to_timestamp(n.datetime::double precision)::date + '24:00:00'::interval)::timestamp with time zone
                        ELSE to_timestamp(n.event_end::double precision)
                    END AS "end",
                n.full_day::integer::boolean AS allday,
                html_unescape(n.title) AS title,
                NULLIF(btrim(n.organizer_simple::text, ' '::text), ''::text) AS organizer,
                NULLIF(btrim(n.location_simple::text, ' '::text), ''::text) AS location,
                html_unescape(n.teaser) AS teaser,
                html_unescape(n.bodytext) AS body,
                regexp_split_to_array(NULLIF(btrim(n.keywords), ''::text), '\s*,\s*'::text) AS keywords,
                NULLIF(btrim(n.description), ''::text) AS description,
                    CASE
                        WHEN n.sys_language_uid > 0 THEN n.sys_language_uid
                        ELSE NULL::integer
                    END AS language_id,
                n.register::integer::boolean AS register,
                    CASE
                        WHEN n.registration_end > 0 THEN to_timestamp(n.registration_end::double precision)
                        ELSE NULL::timestamp with time zone
                    END AS registration_end,
                n.attendingfees::integer::boolean AS attending_fees,
                NULLIF(btrim(n.attendingfees_info), ''::text) AS attending_fees_info,
                NULLIF(btrim(n.www::text, ' '::text), ''::text) AS link,
                    CASE
                        WHEN n.dfppoints > 0 THEN n.dfppoints
                        ELSE NULL::integer
                    END AS dfp_points,
                NULLIF(btrim(n.contact_name::text, ' '::text), ''::text) AS contact,
                NULLIF(btrim(n.contact_email::text, ' '::text), ''::text) AS email,
                to_timestamp(n.tstamp::double precision) AS last_modified,
                (
                    SELECT fr.uid_local
                    FROM typo3.file_reference fr
                    WHERE
                        fr.uid_foreign = n.uid AND
                        fr.tablenames::text = 'tx_news_domain_model_news'::text AND
                        fr.fieldname::text = 'fal_media'::text AND
                        fr.showinpreview = 1 AND
                        fr.hidden = 0 AND
                        fr.deleted = 0
                    ORDER BY fr.sorting
                    LIMIT 1
                ) AS header_image_id
            FROM typo3.news n
            WHERE
                n.datetime <> 0 AND
                (n.starttime = 0 OR n.starttime::double precision > date_part('epoch'::text, now())) AND
                CASE n.event_end
                    WHEN 0 THEN
                        n.datetime + 86400
                    ELSE
                        n.event_end
                    END > date_part('epoch'::text, now()) AND
                n.deleted = 0 AND
                n.hidden = 0 AND
                n.t3ver_wsid = 0 AND
                n.is_event = 1
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_event";
            """,
        ),
    ]

    dependencies = [
        ("typo3", "0012_news_related_links"),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
