# Generated by Django 2.2.28 on 2025-01-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    ops = [
        (
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_event";
            """,
            """
            CREATE MATERIALIZED VIEW public.typo3_event AS
            SELECT n.uid AS id,
                n.pid AS source_id,
                to_timestamp(n.datetime::double precision) AS start,
                    CASE n.event_end
                        WHEN 0 THEN (to_timestamp(n.datetime::double precision)::date + '24:00:00'::interval)::timestamp with time zone
                        ELSE to_timestamp(n.event_end::double precision)
                    END AS "end",
                n.full_day::integer::boolean AS allday,
                html_unescape(n.title) AS title,
                NULLIF(btrim(n.organizer_simple::text, ' '::text), ''::text) AS organizer,
                NULLIF(btrim(n.location_simple::text, ' '::text), ''::text) AS location,
                html_unescape(n.teaser) AS teaser,
                html_unescape(n.bodytext) AS body,
                regexp_split_to_array(NULLIF(btrim(n.keywords), ''::text), '\s*,\s*'::text) AS keywords,
                NULLIF(btrim(n.description), ''::text) AS description,
                    CASE
                        WHEN n.sys_language_uid > 0 THEN n.sys_language_uid
                        ELSE NULL::integer
                    END AS language_id,
                n.register::integer::boolean AS register,
                    CASE
                        WHEN n.registration_end > 0 THEN to_timestamp(n.registration_end::double precision)
                        ELSE NULL::timestamp with time zone
                    END AS registration_end,
                n.attendingfees::integer::boolean AS attending_fees,
                NULLIF(btrim(n.attendingfees_info), ''::text) AS attending_fees_info,
                NULLIF(btrim(n.www::text, ' '::text), ''::text) AS link,
                    CASE
                        WHEN n.dfppoints > 0 THEN n.dfppoints
                        ELSE NULL::integer
                    END AS dfp_points,
                NULLIF(btrim(n.contact_name::text, ' '::text), ''::text) AS contact,
                NULLIF(btrim(n.contact_email::text, ' '::text), ''::text) AS email,
                to_timestamp(n.tstamp::double precision) AS last_modified,
                (
                    SELECT fr.uid_local
                    FROM typo3.file_reference fr
                    WHERE
                        fr.uid_foreign = n.uid AND
                        fr.tablenames::text = 'tx_news_domain_model_news'::text AND
                        fr.fieldname::text = 'fal_media'::text AND
                        fr.showinpreview = 1 AND
                        fr.hidden = 0 AND
                        fr.deleted = 0
                    ORDER BY fr.sorting
                    LIMIT 1
                ) AS header_image_id
            FROM typo3.news n
            WHERE
                n.datetime <> 0 AND
                (n.starttime = 0 OR n.starttime::double precision > date_part('epoch'::text, now())) AND
                CASE n.event_end
                    WHEN 0 THEN
                        n.datetime + 86400
                    ELSE
                        n.event_end
                    END > date_part('epoch'::text, now()) AND
                n.deleted = 0 AND
                n.hidden = 0 AND
                n.t3ver_wsid = 0 AND
                n.is_event = 1
            WITH DATA;
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW public.typo3_event AS
            SELECT n.uid AS id,
                n.pid AS source_id,
                to_timestamp(n.datetime::double precision) AS start,
                    CASE n.event_end
                        WHEN 0 THEN (to_timestamp(n.datetime::double precision)::date + '24:00:00'::interval)::timestamp with time zone
                        ELSE to_timestamp(n.event_end::double precision)
                    END AS "end",
                n.full_day::integer::boolean AS allday,
                html_unescape(n.title) AS title,
                NULLIF(btrim(n.organizer_simple::text, ' '::text), ''::text) AS organizer,
                NULLIF(btrim(n.location_simple::text, ' '::text), ''::text) AS location,
                html_unescape(n.teaser) AS teaser,
                html_unescape(n.bodytext) AS body,
                regexp_split_to_array(NULLIF(btrim(n.keywords), ''::text), '\s*,\s*'::text) AS keywords,
                NULLIF(btrim(n.description), ''::text) AS description,
                    CASE
                        WHEN n.sys_language_uid > 0 THEN n.sys_language_uid
                        ELSE NULL::integer
                    END AS language_id,
                n.register::integer::boolean AS register,
                    CASE
                        WHEN n.registration_end > 0 THEN to_timestamp(n.registration_end::double precision)
                        ELSE NULL::timestamp with time zone
                    END AS registration_end,
                n.attendingfees::integer::boolean AS attending_fees,
                NULLIF(btrim(n.attendingfees_info), ''::text) AS attending_fees_info,
                NULLIF(btrim(n.www::text, ' '::text), ''::text) AS link,
                    CASE
                        WHEN n.dfppoints > 0 THEN n.dfppoints
                        ELSE NULL::integer
                    END AS dfp_points,
                NULLIF(btrim(n.contact_name::text, ' '::text), ''::text) AS contact,
                NULLIF(btrim(n.contact_email::text, ' '::text), ''::text) AS email,
                to_timestamp(n.tstamp::double precision) AS last_modified,
                (
                    SELECT fr.uid_local
                    FROM typo3.file_reference fr
                    WHERE
                        fr.uid_foreign = n.uid AND
                        fr.tablenames::text = 'tx_news_domain_model_news'::text AND
                        fr.fieldname::text = 'fal_media'::text AND
                        fr.showinpreview = 1 AND
                        fr.hidden = 0 AND
                        fr.deleted = 0
                    ORDER BY fr.sorting
                    LIMIT 1
                ) AS header_image_id
            FROM typo3.news n
            WHERE
                n.datetime <> 0 AND
                n.deleted = 0 AND
                n.hidden = 0 AND
                n.t3ver_wsid = 0 AND
                n.is_event = 1
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_event";
            """,
        ),
    ]

    dependencies = [
        ("typo3", "0014_event_related_fields"),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
