# Generated by Django 2.2.28 on 2025-02-07 08:04

from django.db import migrations


class Migration(migrations.Migration):

    ops = [
        (
            """
            DROP VIEW IF EXISTS "public"."typo3_eventcategory";
            """,
            """
	        CREATE VIEW "public"."typo3_eventcategory" AS
            SELECT
                concat(cr.uid_local, '-', cr.uid_foreign) AS id,
                cr.uid_local AS category_id,
                cr.uid_foreign AS event_id
            FROM
                typo3.category_record cr
            JOIN
                typo3.news n ON (n.uid = cr.uid_foreign)
            WHERE
                cr.tablenames = 'tx_news_domain_model_news'
                AND
                n.datetime <> 0
                AND
                n.event_end <> 0
                AND
                (
                    n.starttime = 0
                    OR
                    n.starttime > date_part('epoch'::text, now())
                )
                AND
                (
                    CASE
                        n.full_day
                    WHEN
                        1
                    THEN
                        n.event_end + 86400
                    ELSE
                        n.event_end
                    END
                ) > date_part('epoch'::text, now())
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 1
            """,
        ),
        (
            """
            CREATE VIEW "public"."typo3_eventcategory" AS
            SELECT
                concat(cr.uid_local, '-', cr.uid_foreign) AS id,
                cr.uid_local AS category_id,
                cr.uid_foreign AS event_id
            FROM
                typo3.category_record cr
            JOIN
                typo3.news n ON (n.uid = cr.uid_foreign)
            WHERE
                cr.tablenames = 'tx_news_domain_model_news'
                AND
                n.datetime <> 0
                AND
                n.event_end <> 0
                AND
                n.deleted = 0
                AND
                n.hidden = 0
                AND
                n.is_event = 1
            """,
            """
            DROP VIEW IF EXISTS "public"."typo3_eventcategory";
            """,
        ),
    ]

    dependencies = [
        ("typo3", "0015_event_no_filter"),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
