# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-17 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    ops = [
        (
            """
            DROP INDEX IF EXISTS typo3_event_id_idx;
            """,
            """
            CREATE UNIQUE INDEX typo3_event_id_idx ON "public"."typo3_event" ("id");
            """,
        ),
        (
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_event";
            """,
            """
            CREATE MATERIALIZED VIEW "public"."typo3_event" AS SELECT
                event.uid AS id,
                event.pid AS source_id,
                to_date(event.start_date::text, 'YYYYMMDD'::text) +
                CASE event.allday
                    WHEN 1 THEN '00:00:00'::interval
                    ELSE event.start_time::double precision * '00:00:01'::interval
                END AS start,
                to_date(event.end_date::text, 'YYYYMMDD'::text) +
                CASE event.allday
                    WHEN 1 THEN '24:00:00'::interval
                    ELSE event.end_time::double precision * '00:00:01'::interval
                END AS "end",
                event.allday::boolean AS allday,
                html_unescape(event.title) AS title,
                event.calendar_id,
                CASE
                    WHEN event.category_id > 0 THEN event.category_id
                    ELSE NULL::integer
                END AS category_id,
                event.organizer,
                event.location,
                html_unescape(event.teaser) AS teaser,
                html_unescape(event.description) AS description,
                CASE
                    WHEN event.sys_language_uid > 0 THEN event.sys_language_uid
                    ELSE NULL::integer
                END AS language_id,
                event.tx_mugcal_register::boolean AS register,
                CASE
                    WHEN event.tx_mugcal_registration_end > 0 THEN to_timestamp(event.tx_mugcal_registration_end::double precision)
                    ELSE NULL::timestamp with time zone
                END AS registration_end,
                event.tx_mugcal_attendingfees::boolean AS attending_fees,
                event.tx_mugcal_www AS link,
                event.tx_mugcal_dfppoints AS dfp_points,
                event.tx_mugcal_contact AS contact,
                event.tx_mugcal_contact_email AS email,
                to_timestamp(event.tstamp::double precision) AS last_modified
            FROM typo3.event
            WHERE
                event.start_date::text <> '0'::text AND
                event.end_date::text <> '0'::text AND (
                    event.starttime = 0 OR
                    to_timestamp(event.starttime::double precision) > now()
                ) AND
                (
                    to_date(event.end_date::text, 'YYYYMMDD'::text) +
                    CASE event.allday
                        WHEN 1 THEN '24:00:00'::interval
                        ELSE event.end_time::double precision * '00:00:01'::interval
                    END
                ) > now() AND
                event.deleted = 0 AND
                event.hidden = 0
            WITH DATA;
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."typo3_event" AS SELECT
                event.uid AS id,
                event.pid AS source_id,
                to_date(event.start_date::text, 'YYYYMMDD'::text) +
                CASE event.allday
                    WHEN 1 THEN '00:00:00'::interval
                    ELSE event.start_time::double precision * '00:00:01'::interval
                END AS start,
                to_date(event.end_date::text, 'YYYYMMDD'::text) +
                CASE event.allday
                    WHEN 1 THEN '24:00:00'::interval
                    ELSE event.end_time::double precision * '00:00:01'::interval
                END AS "end",
                event.allday::boolean AS allday,
                html_unescape(event.title) AS title,
                event.calendar_id,
                CASE
                    WHEN event.category_id > 0 THEN event.category_id
                    ELSE NULL::integer
                END AS category_id,
                event.organizer,
                event.location,
                html_unescape(event.teaser) AS teaser,
                html_unescape(event.description) AS description,
                CASE
                    WHEN event.sys_language_uid > 0 THEN event.sys_language_uid
                    ELSE NULL::integer
                END AS language_id,
                event.tx_mugcal_register::boolean AS register,
                CASE
                    WHEN event.tx_mugcal_registration_end > 0 THEN to_timestamp(event.tx_mugcal_registration_end::double precision)
                    ELSE NULL::timestamp with time zone
                END AS registration_end,
                event.tx_mugcal_attendingfees::boolean AS attending_fees,
                event.tx_mugcal_www AS link,
                CASE
                    WHEN event.tx_mugcal_dfppoints > 0 THEN event.tx_mugcal_dfppoints
                    ELSE NULL
                END AS dfp_points,
                event.tx_mugcal_contact AS contact,
                event.tx_mugcal_contact_email AS email,
                to_timestamp(event.tstamp::double precision) AS last_modified
            FROM typo3.event
            WHERE
                event.start_date::text <> '0'::text AND
                event.end_date::text <> '0'::text AND (
                    event.starttime = 0 OR
                    to_timestamp(event.starttime::double precision) > now()
                ) AND
                (
                    to_date(event.end_date::text, 'YYYYMMDD'::text) +
                    CASE event.allday
                        WHEN 1 THEN '24:00:00'::interval
                        ELSE event.end_time::double precision * '00:00:01'::interval
                    END
                ) > now() AND
                event.deleted = 0 AND
                event.hidden = 0
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_event";
            """,
        ),
        (
            """
            CREATE UNIQUE INDEX typo3_event_id_idx ON "public"."typo3_event" ("id");
            """,
            """
            DROP INDEX IF EXISTS typo3_event_id_idx;
            """,
        ),
    ]

    dependencies = [("typo3", "0023_auto_20190122_1456")]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
