# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 07:49
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    ops = [
        (
            """
            CREATE FOREIGN TABLE "typo3"."zmf_course" (
                uid integer,
                pid integer,
                tstamp integer,
                crdate integer,
                sorting integer,
                deleted integer,
                hidden integer,
                sys_language_uid integer,
                l10n_parent integer,
                title varchar,
                bodytext varchar,
                email varchar,
                module integer,
                categories integer
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'tx_mugzmfcourses_domain_model_course',
                db_url '{}'
            );
            """.format(
                settings.MULTICORN.get("typo3")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "typo3"."zmf_course";
            """,
        ),
        (

            """
            CREATE VIEW "public"."typo3_zmf_course" AS
            SELECT
                t.uid AS id,
                t.pid AS page,
                to_timestamp(t.tstamp::double precision) AS last_modified,
                to_timestamp(t.crdate::double precision) AS created,
                t.sorting AS sorting,
                CASE
                    WHEN t.sys_language_uid > 0 THEN t.sys_language_uid
                    ELSE NULL::integer
                END AS language_id,
                CASE
                    WHEN t.sys_language_uid > 0 THEN t.l10n_parent
                    ELSE NULL::integer
                END AS language_parent_id,
                title AS title,
                NULLIF(bodytext, '') AS description,
                email AS email,
                NULLIF(module, 0) AS module_id,
                categories AS category_id
            FROM "typo3"."zmf_course" AS t
            WHERE t.deleted = 0 AND t.hidden = 0
            """,
            """
            DROP VIEW IF EXISTS "public"."typo3_zmf_course";
            """
        ),

    ]

    dependencies = [
        ('typo3', '0024_dfp_points'),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
