# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typo3', '0025_zmf_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZMFCourse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('page', models.IntegerField()),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'typo3_zmf_course',
                'managed': False,
            },
        ),
    ]
